### PR TITLE
fix(file-io): Do not leak SentryFileInputStream/SentryFileOutputStream descriptors and channels

### LINKED ISSUE #2905: The application crashes with StrictMode error after sentry initialization on android api 31, 32, 33.
### Integration

sentry-android

### Build System

Gradle

### AGP Version

7.4.1

### Proguard

Enabled

### Version

6.27.0

### Steps to Reproduce

**The application crashes with StrictMode error after sentry initialization on android api 31, 32, 33.**
**StrictMode** policy for detect the SQL leaked, the closable objects leaked and detecting network operations.

Apparently, the issue is related to "android.appcompat:appcompat-resources:1.4.2 and android.appcompat:appcompat:1.4.2" entries present in the sentry-external-modules.txt file.

Sentry plugin version: 3.11.1; sentry version: 6.27.0 (6.28.0 dont' fix this problem); targetAndroidSdkVersion 31; minAndroidSdkVersion 24

Error example: 

```
StrictMode policy violation: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                                                                    	at android.os.StrictMode$AndroidCloseGuardReporter.report(StrictMode.java:1987)
                                                                                                    	at dalvik.system.CloseGuard.warnIfOpen(CloseGuard.java:336)
                                                                                                    	at sun.nio.ch.FileChannelImpl.finalize(FileChannelImpl.java:175)
                                                                                                    	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:319)
                                                                                                    	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:306)
                                                                                                    	at java.lang.Daemons$Daemon.run(Daemons.java:140)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    Caused by: java.lang.Throwable: Explicit termination method 'close' not called
                                                                                                    	at dalvik.system.CloseGuard.openWithCallSite(CloseGuard.java:288)
                                                                                                    	at dalvik.system.CloseGuard.open(CloseGuard.java:257)
                                                                                                    	at sun.nio.ch.FileChannelImpl.<init>(FileChannelImpl.java:110)
                                                                                                    	at sun.nio.ch.FileChannelImpl.open(FileChannelImpl.java:120)
                                                                                                    	at java.io.FileInputStream.getChannel(FileInputStream.java:475)
                                                                                                    	at androidx.core.graphics.TypefaceCompatUtil.mmap(TypefaceCompatUtil.java:115)
                                                                                                    	at androidx.emoji2.text.FontRequestEmojiCompatConfig$FontRequestMetadataLoader.createMetadata(FontRequestEmojiCompatConfig.java:381)
                                                                                                    	at androidx.emoji2.text.FontRequestEmojiCompatConfig$FontRequestMetadataLoader$$ExternalSyntheticLambda0.run(Unknown Source:2)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012) 
```

### Expected Result

There are no memory leaks.

### Actual Result

There are memory leaks.

### PR DESCRIPTION
**Pull request by romtsn**
## :scroll: Description

- We forgot to call `close` in SentryFIOStream, and were just calling `delegate.close` but the associated channels and file descriptors were still leaking for our streams
- Changed `addAttachment` sample so it uses a FileChannel (this is how I managed to reproduce the strict mode violation)

## :bulb: Motivation and Context

Closes #2905 

## :green_heart: How did you test it?
Manually + automated

## :pencil: Checklist

- [x] I added tests to verify the changes.
- [x] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled.
- [x] I updated the docs if needed.
- [x] I updated the wizard if needed.
- [x] Review from the native team if needed.
- [x] No breaking change or entry added to the changelog.
- [x] No breaking change for hybrid SDKs or communicated to hybrid SDKs.

### CODE REVIEW

File: sentry-samples/sentry-samples-android/src/main/java/io/sentry/samples/android/MainActivity.java [hunk 1]
```diff
@@ -86,16 +83,10 @@ protected void onCreate(Bundle savedInstanceState) {
...
-            for (int i = 0; i < 1024; i++) {
-              // To keep the sample code simple this happens on the main thread. Don't do this in a
-              // real app.
-              writer.write(String.format(Locale.getDefault(), "%d\n", i));
-            }
-            writer.flush();
+          try (final FileOutputStream fis =
+              SentryFileOutputStream.Factory.create(new FileOutputStream(file), file)) {
+            FileChannel channel = fis.getChannel();
+            channel.write(java.nio.ByteBuffer.wrap("Hello, World!".getBytes()));
```
Comment (stefanosiano) [inline sentry-samples/sentry-samples-android/src/main/java/io/sentry/samples/android/MainActivity.java:89]:
```suggestion
          try (final FileOutputStream fos =
              SentryFileOutputStream.Factory.create(new FileOutputStream(file), file)) {
            FileChannel channel = fos.getChannel();
            channel.write(java.nio.ByteBuffer.wrap("Hello, World!".getBytes()));
```

**Review by stefanosiano — APPROVED** [review]
