### PR TITLE
fix(replay): Fix crash when root view has no window or is too small

### LINKED ISSUE #4548: Session Replay with invisible windows doesn't work
### Description

Smartlook adds an invisible (0-sized?) window on top of the screen to do their shenanigans. Because of that our root view detector fails. It might be something sketchy they are doing and we just need a troubleshooting entry, but perhaps there's a way to fix this on our side.

### LINKED ISSUE #4802: Session Replay IllegalArgumentException: width and height must be > 0 when launching in-app review prompt
### Integration

sentry-android

### Build System

Gradle

### AGP Version

8.11.1

### Proguard

Enabled

### Version

8.21.0

### Steps to Reproduce

This crash occurs whenever the Google Play In-App Review prompt is shown [(See Google's overview here)](https://developer.android.com/guide/playcore/in-app-review) with Sentry's Session Replay enabled. 

Unfortunately, creating a minimally reproducible app to share is not possible, given for one to show this prompt per Google ([See its test in-app reviews documentation](https://developer.android.com/guide/playcore/in-app-review/test#troubleshooting)), they must:

1. Have an app that is published on Google Play or, at a minimum, on an internal testing track
2. Have not already reviewed the published app
3. Have an account that is able to review the app. A personal Gmail account that is allowlisted to test in Google Play's internal test track is easiest here, as if your organization is using Google Workspace accounts they often do not have permissions to leave a review.

Once those requirements are met, this is reproducible by:

1. Enabling Sentry's Session Replay for Android in a Compose UI app
2. Launching the in-app review flow ([See documentation)](https://developer.android.com/guide/playcore/in-app-review/kotlin-java#launch-review-flow)
3. Seeing the crash

### Expected Result

The in-app review prompt should display without crashing.

### Actual Result

The following exception occurs when the Google Play review prompt is shown:
```
FATAL EXCEPTION: main
Process: com.bennyapp.benny, PID: 4961

java.lang.IllegalArgumentException: width and height must be > 0
    at android.graphics.Bitmap.createBitmap(Bitmap.java:1239)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:1205)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:1153)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:1112)
    at io.sentry.android.replay.ScreenshotRecorder.<init>(ScreenshotRecorder.kt:52)
    at io.sentry.android.replay.WindowRecorder.onConfigurationChanged(WindowRecorder.kt:181)
    at io.sentry.android.replay.ReplayIntegration.onConfigurationChanged(ReplayIntegration.kt:491)
    at io.sentry.android.replay.ReplayIntegration.onWindowSizeChanged(ReplayIntegration.kt:482)
    at io.sentry.android.replay.WindowRecorder$determineWindowSize$1.onPreDraw(WindowRecorder.kt:151)
    at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1179)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4417)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3076)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10643)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1570)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1579)
    at android.view.Choreographer.doCallbacks(Choreographer.java:1179)
    at android.view.Choreographer.doFrame(Choreographer.java:1108)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1553)
    at android.os.Handler.handleCallback(Handler.java:995)
    at android.os.Handler.dispatchMessage(Handler.java:103)
    at android.os.Looper.loopOnce(Looper.java:248)
    at android.os.Looper.loop(Looper.java:338)
    at android.app.ActivityThread.main(ActivityThread.java:9067)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:593)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:932)
```
This crashes our app and leaves the review prompt shown:

### PR DESCRIPTION
**Pull request by romtsn**
## :scroll: Description

- Set minimum screenshot size to 16 (minimum block size for encoding)
- Check earlier if a root view has an associated window - if not, then we cannot take screenshots of it and should not even track it

## :bulb: Motivation and Context

Closes #4548 
Closes #4802 

## :green_heart: How did you test it?
Manually using smartlook (which adds an invisible window on top), it's a bit tricky to unit test it

## :pencil: Checklist

- [x] I added GH Issue ID _&_ Linear ID
- [ ] I added tests to verify the changes.
- [ ] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled.
- [ ] I updated the docs if needed.
- [ ] I updated the wizard if needed.
- [ ] Review from the native team if needed.
- [ ] No breaking change or entry added to the changelog.
- [ ] No breaking change for hybrid SDKs or communicated to hybrid SDKs.

### CODE REVIEW

File: sentry-android-replay/src/main/java/io/sentry/android/replay/WindowRecorder.kt [hunk 1]
```diff
@@ -110,6 +110,11 @@ internal class WindowRecorder(
   override fun onRootViewsChanged(root: View, added: Boolean) {
     rootViewsLock.acquire().use {
       if (added) {
+        if (root.phoneWindow == null) {
```
Comment (romtsn) [inline sentry-android-replay/src/main/java/io/sentry/android/replay/WindowRecorder.kt:113]: @markushi not sure if this is a problem for the CanvasStrategy - or can it actually still capture this cases?

Comment (markushi) [reply sentry-android-replay/src/main/java/io/sentry/android/replay/WindowRecorder.kt:113]: Hmm we already check [for this over here](https://github.com/getsentry/sentry-java/blob/main/sentry-android-replay/src/main/java/io/sentry/android/replay/ScreenshotRecorder.kt#L93-L97). I guess the phoneWindow can be null when the view is detached or maybe rendered offscreen?

Comment (romtsn) [reply sentry-android-replay/src/main/java/io/sentry/android/replay/WindowRecorder.kt:113]: right, but my idea was that it's too late to check in ScreenshotRecorder already, because we basically wouldn't capture anything. But when we do this check early enough (here), we don't even track that window and just keep capturing the last known visible one.

Comment (markushi) [reply sentry-android-replay/src/main/java/io/sentry/android/replay/WindowRecorder.kt:113]: Ah ok, yeah that makes sense!
