### PR TITLE
Fix: Set Span status for OkHttp integration

### LINKED ISSUE #1421: Span status for OkHttp integration
https://github.com/getsentry/develop/issues/307#issuecomment-822240763

### PR DESCRIPTION
**Pull request by maciejwalkowiak**
## :scroll: Description

Fix: Set Span status for OkHttp integration

## :bulb: Motivation and Context

Fixes #1421 

## :green_heart: How did you test it?

Unit tests.

## :pencil: Checklist

- [x] I reviewed the submitted code
- [x] I added tests to verify the changes
- [ ] I updated the docs if needed
- [x] No breaking changes

### CODE REVIEW

File: sentry-android-okhttp/src/test/java/io/sentry/android/okhttp/SentryOkHttpInterceptorTest.kt [hunk 1]
```diff
@@ -38,66 +40,76 @@ class SentryOkHttpInterceptorTest {
             whenever(hub.options).thenReturn(SentryOptions())
         }
 
-        fun getSut(isSpanActive: Boolean = true, httpStatusCode: Int = 201, responseBody: String = "success"): OkHttpClient {
+        fun getSut(isSpanActive: Boolean = true, httpStatusCode: Int = 201, responseBody: String = "success", socketPolicy: SocketPolicy = SocketPolicy.KEEP_OPEN): OkHttpClient {
```
Comment (marandaneto) [inline sentry-android-okhttp/src/test/java/io/sentry/android/okhttp/SentryOkHttpInterceptorTest.kt:43]: just out of curiosity, why do we need `SocketPolicy`?

**Review by marandaneto — APPROVED** [review]
LGTM

File: sentry-android-okhttp/src/test/java/io/sentry/android/okhttp/SentryOkHttpInterceptorTest.kt (hunk 1 above)
Comment (maciejwalkowiak) [reply sentry-android-okhttp/src/test/java/io/sentry/android/okhttp/SentryOkHttpInterceptorTest.kt:43]: To trigger IOException
