### PR TITLE
Fix: Move tags from transaction.contexts.trace.tags to transaction.tags

### LINKED ISSUE #1693: `transaction.contexts.trace.tags` should go under `transaction.tags`
right now the transaction tags go under `transaction.contexts.trace.tags` but it should go under `transaction.tags`

`transaction.contexts.trace` should only have a few fields which are documented here https://develop.sentry.dev/sdk/event-payloads/transaction/#examples

### PR DESCRIPTION
**Pull request by maciejwalkowiak**
## :scroll: Description

Move tags from `transaction.contexts.trace.tags` to `transaction.tags`.

## :bulb: Motivation and Context

Fixes #1693

The implementation could be cleaner - like introducing a dedicated `TraceContext` object, but this would mean we introduce a breaking change - something to keep in mind for 6.0.

## :green_heart: How did you test it?

Unit tests.

## :pencil: Checklist

- [x] I reviewed the submitted code
- [x] I added tests to verify the changes
- [ ] I updated the docs if needed
- [x] No breaking changes

### CODE REVIEW

File: sentry/src/test/java/io/sentry/SentryTracerTest.kt [hunk 1]
```diff
@@ -298,9 +328,11 @@ class SentryTracerTest {
         transaction.finish(SpanStatus.UNKNOWN_ERROR)
 
         // call only once
-        verify(fixture.hub).setSpanContext(ex, transaction.root, "name")
-        verify(fixture.hub).captureTransaction(check {
-            assertEquals(transaction.root.spanContext, it.contexts.trace)
+        verify(fixture.hub, times(1)).setSpanContext(ex, transaction.root, "name")
+        verify(fixture.hub, times(1)).captureTransaction(check {
```
Comment (marandaneto) [inline sentry/src/test/java/io/sentry/SentryTracerTest.kt:332]: iirc `times(1)` is the default value, we can remove it

**Review by marandaneto — APPROVED** [review]
left a comment but rather than that LGTM, thanks @maciejwalkowiak
