### PR TITLE
Fix #671 Use buildType.ext to override org and project 

### LINKED ISSUE #671: Separate sentry project for each android build type
Is it possible to use multiple sentry projects with sentry gradle plugin? 
[Docs](https://docs.sentry.io/cli/configuration/#config-defaults) say that `default.project` option must be defined in `sentry.properties` that is placed in the root dir of a project.

My app uses two build types e.g (`release` and `staging`). Each type uses Proguard for obfuscation. And I want to set different sentry projects for them. 

How do I make crashes from `release` be sent to `myapp-release` sentry project and crashes from `staging` be sent to `myapp-staging`?

### PR DESCRIPTION
**Pull request by nesterov-n**
This fixes #671 

Adds ability to use separate sentry projects and orgs for different application build types. Use 
ext params of Android buildTypes: 
- `sentryOrg` 
- `sentryProject`

For example. Let's assume android project: 
`sentry.properties` in the project root: 
```
defaults.project=my-app
defaults.org=my-org
auth=<api_token>
```

and `build.gradle`:
```
...
android {
    buildTypes { 
         release { ... }
         staging {
            ext {
                set("sentryProject", "my-app-staging")
            }
         ....
         }
         experimental {
            ext {
                set("sentryProject", "my-app-experimental")
                set("sentryOrg", "my-org-experimental")
            }
         }

    }
```

Proguard mapping for release build type is uploaded to  `my-app` project of `my-org` (defaults)
staging to `my-app-staging` project of `my-org`
and experimental to `my-app-experimental` of `my-org-experimental`

The weakest point of this approach is using string parameter names for configuration. 
Another way: With gradle mixins, we can achieve strong typing:
```
experimental {
    sentryOrg "my-org-experimental"
    sentryProject "my-app-experimental"
}
```

But this approach requires the android application plugin being applied before the sentry plugin. 
build.gradle like this will fail: 
```
plugins {
    id("sentry")
    id("com.android.application")
}
```

### CODE REVIEW

File: sentry-android-gradle-plugin/src/main/groovy/io/sentry/android/gradle/SentryPlugin.groovy [hunk 1]
```diff
@@ -244,7 +246,17 @@ class SentryPlugin implements Plugin<Project> {
                         ]
 
                         if (!extension.autoUpload) {
-                            args.push("--no-upload")
+                            args.add("--no-upload")
```
Comment (nesterov-n) [inline sentry-android-gradle-plugin/src/main/groovy/io/sentry/android/gradle/SentryPlugin.groovy]: changes from #669 to make this works with gradle 5.x
