### PR TITLE
Encode SDK_VERSION in a Java class instead of looking up a ResouceBun…

### LINKED ISSUE #605: Sentry.init blocks main thread on startup to retrieve SDK version number (android)
[The Android integration documentation](https://docs.sentry.io/clients/java/modules/android/) suggests that `Sentry.init` should be called on startup. However, `Sentry.init` blocks the main thread for an extended period of time – 463ms wall clock time and 219ms CPU time on a Fire TV 4K – which is notably half of our `Activity.onCreate` run time:
screen shot 2018-08-31 at 14 08 16

Here's the trace file: [startup.trace.tar.gz](https://github.com/getsentry/sentry-java/files/2341629/startup.trace.tar.gz)

Looking to the Sentry call stack:
screen shot 2018-08-31 at 14 15 08

It looks like this line is causing the blocking call: https://github.com/getsentry/sentry-java/blob/33f8b7edb41879a9e669aa863a7abfbb79247aa0/sentry/src/main/java/io/sentry/environment/SentryEnvironment.java#L23

Which is reading the JAR. Notes:
- This is a long time to wait for an SDK version, especially on startup; I'd rather this be filled asynchronously and potentially have a few crash reports without SDK versions (especially because I can often identify the sdk version by app version)
- My assumption is that reading the JAR reads from disk and reading from disk on the main thread in Android is generally frowned upon

---

STR
- Clone my [firefox-tv/host-startup-trace branch](https://github.com/mcomella/firefox-tv/tree/host-startup-trace)
- Launch and run on device until UI appears
- Filter logcat for "lol", you should see a path to a file
- Extract the file (e.g. with Android Studio's device file explorer which can access private dirs or `adb pull`)
- Open and examine trace in AS

### PR DESCRIPTION
**Pull request by bretthoerner**
…dle.

Fixes #605 and replaces #607.

### CODE REVIEW

File: sentry/src/main/java-templates/io/sentry/environment/Version.java [hunk 1]
```diff
@@ -0,0 +1,9 @@
+package io.sentry.environment;
```
Comment (ncalexan) [inline sentry/src/main/java-templates/io/sentry/environment/Version.java]: No license block?

File: sentry/src/main/java/io/sentry/environment/SentryEnvironment.java [hunk 2]
```diff
@@ -20,7 +19,7 @@
     /**
      * Version of this SDK.
      */
-    public static final String SDK_VERSION = ResourceBundle.getBundle("sentry-build").getString("build.name");
+    public static final String SDK_VERSION = Version.SDK_VERSION;
```
Comment (ncalexan) [inline sentry/src/main/java/io/sentry/environment/SentryEnvironment.java]: If you're doing this globally (i.e., on the JVM as well as on Android), shouldn't you be removing the bundle and the build-time processing of it?  Or are you adding this as an alternate option only, or doing a staged deprecation?

File: sentry/src/main/java-templates/io/sentry/environment/Version.java [hunk 3]
```diff
@@ -0,0 +1,9 @@
...
+
+public final class Version {
+    public static final String SDK_VERSION = "${project.version}";
```
Comment (ncalexan) [inline sentry/src/main/java-templates/io/sentry/environment/Version.java]: Can you explain why you're using `project.version` here but it was something like `build.name` in the other plugin?  Are these two names for the same thing?

File: sentry/src/main/java-templates/io/sentry/environment/Version.java (hunk 1 above)
Comment (bretthoerner) [reply sentry/src/main/java-templates/io/sentry/environment/Version.java]: Yeah, we don't require those in Sentry projects. One license to rule the project, haha.

File: sentry/src/main/java/io/sentry/environment/SentryEnvironment.java (hunk 2 above)
Comment (bretthoerner) [reply sentry/src/main/java/io/sentry/environment/SentryEnvironment.java]: Ah good point, I guess it's pretty big reach to think someone is manually using our resource for anything. It seems harmless to leave in (as you said, maybe until next major version) or I can just remove it. I'm indifferent tbh.

File: sentry/src/main/java-templates/io/sentry/environment/Version.java (hunk 3 above)
Comment (bretthoerner) [reply sentry/src/main/java-templates/io/sentry/environment/Version.java]: Good catch, `project.version` is a Maven builtin and mental default for me. `buildName` is slightly different as its generated using a plugin and we include the git hash. I may as well maintain the same pattern (and use `buildName`):

https://github.com/getsentry/sentry-java/blob/27d5f6b8ec51bcf97f8d066abcb80e072652573b/sentry/pom.xml#L101-L122

File: sentry/src/main/java/io/sentry/environment/SentryEnvironment.java (hunk 2 above)
Comment (bretthoerner) [reply sentry/src/main/java/io/sentry/environment/SentryEnvironment.java]: Yeah, on a second pass since I'm re-using `$buildNumber` anyway it seems harmless to leave the properties file there until we do a real deprecation.

**Comment by bretthoerner** [comment]
Feeling pretty good about this since doesn't break any backwards compat (my previous issue changed some public static names). I'll give it until tomorrow then push out a release if I don't hear any complaints?
