### PR TITLE
Ignore broken regex for tracePropagationTarget

### LINKED ISSUE #2286: Invalid regex throws `PatternSyntaxException`
### Description

`TracePropagationTargets#contain` uses `url.matches(origin)` but does not check if its a valid regex or try/catch.
Similar to https://github.com/getsentry/sentry-dart/pull/1043
To reproduce, use regex `AABB???` in `tracePropagationTargets`

### PR DESCRIPTION
**Pull request by adinauer**
Wrap regex URL matching for `tracePropagationTargets` with try / catch and ignore exception.

## :bulb: Motivation and Context

Fixes #2286

## :green_heart: How did you test it?
Unit Test

## :pencil: Checklist

- [ ] I reviewed the submitted code
- [ ] I added tests to verify the changes
- [ ] I updated the docs if needed
- [ ] No breaking changes

### CODE REVIEW

File: sentry/src/main/java/io/sentry/TracePropagationTargets.java [hunk 1]
```diff
@@ -15,9 +15,16 @@ public static boolean contain(final @NotNull List<String> origins, final @NotNul
...
     }
     for (final String origin : origins) {
-      if (url.contains(origin) || url.matches(origin)) {
+      if (url.contains(origin)) {
         return true;
       }
+      try {
+        if (url.matches(origin)) {
+          return true;
+        }
```
Comment (romtsn) [inline sentry/src/main/java/io/sentry/TracePropagationTargets.java:24]:
```suggestion
    return url.matches(origin)
```
could be just this?

**Review by romtsn — APPROVED** [review]

File: sentry/src/main/java/io/sentry/TracePropagationTargets.java (hunk 1 above)
Comment (adinauer) [reply sentry/src/main/java/io/sentry/TracePropagationTargets.java]: Oops, no we can't because then we'd just return whether the first entry in the list matches but we want to check all of them and only return `false` if none of them match.
