### PR TITLE
Capture unfinished transactions on crash

### LINKED ISSUE #2316: Finish and capture transaction/span bound to the Scope in case of a fatal crash
### Problem Statement

See https://github.com/getsentry/team-mobile/issues/62 for more details.

### Solution Brainstorm

Finish transaction/span in `UncaughtExceptionHandlerIntegration`

### PR DESCRIPTION
**Pull request by romtsn**
## :scroll: Description

* Keep on the `UncaughtExceptionHint` reference if we know there's an active transaction on scope. This transaction will then use the hint to call `markFlushed` and unblock the main thread once its serialization is done, which happens _after_ the crash has been already serialized

Previously this was possible only if you capture exceptions manually:
image

## :bulb: Motivation and Context

Closes #2316

## :pencil: Checklist

- [x] I reviewed the submitted code.
- [x] I added tests to verify the changes.
- [x] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled.
- [x] I updated the docs if needed.
- [x] Review from the native team if needed.
- [x] No breaking change or entry added to the changelog.
- [x] No breaking change for hybrid SDKs or communicated to hybrid SDKs.

### CODE REVIEW

File: sentry/src/main/java/io/sentry/SentryClient.java [hunk 1]
```diff
@@ -209,14 +210,19 @@ private boolean shouldApplyScopeData(
...
 
-    // if we encountered an abnormal exit finish tracing in order to persist and send
+    // if we encountered a crash/abnormal exit finish tracing in order to persist and send
     // any running transaction / profiling data
     if (scope != null) {
-      @Nullable ITransaction transaction = scope.getTransaction();
+      final @Nullable ITransaction transaction = scope.getTransaction();
       if (transaction != null) {
-        // TODO if we want to do the same for crashes, e.g. check for event.isCrashed()
         if (HintUtils.hasType(hint, TransactionEnd.class)) {
```
Comment (adinauer) [inline sentry/src/main/java/io/sentry/SentryClient.java:218]: I'm assuming there's no risk of this firing multiple times, leading to multiple forceFinish invocations where the root span hasn't yet been marked as finished before consecutive invocations, correct?

**Review by adinauer — APPROVED** [review]
Given there's no problem with the code where I added an assumption this LGTM after giving it a quick pass.

**Review by stefanosiano — APPROVED** [review]
looks good!
