### PR TITLE
Fix: set user on transaction

### LINKED ISSUE #1335: User is not set on transactions

### PR DESCRIPTION
**Pull request by maciejwalkowiak**
## :scroll: Description

Set user on transaction.

User is set on the scope in Servlet filter - `SentryUserFilter`. This filter must run after Spring security (or any other filter verifying authentication details) so that `SentryUserProvider` implementations can access the currently logged in user data.

Sentry request flow

In Spring Boot integration, `SentryUserFilter` is set to run:

- by default runs as the last filter (lowest precedence)
- user can explicitly define the order

In Spring integration, filter bean must be created manually and a corresponding `DelegatingFilterProxy` servlet filter must be registered.

## :bulb: Motivation and Context

Fixes #1335 

## :pencil: Checklist

- [x] I reviewed the submitted code
- [x] I added tests to verify the changes
- [ ] I updated the docs if needed
- [x] No breaking changes

### CODE REVIEW

File: sentry-spring-boot-starter/src/main/java/io/sentry/spring/boot/SentryAutoConfiguration.java [hunk 1]
```diff
@@ -125,6 +130,43 @@
     @Open
     static class SentryWebMvcConfiguration {
 
+      @Bean
```
Comment (bruno-garcia) [inline sentry-spring-boot-starter/src/main/java/io/sentry/spring/boot/SentryAutoConfiguration.java:133]: Missing Javadocs on this one?

File: CHANGELOG.md [hunk 2]
```diff
@@ -12,6 +12,7 @@
 * Fix: Pass maxBreadcrumbs config. to sentry-native (#1425)
 * Fix: Run event processors and enrich transactions with contexts (#1430)
 * Bump: sentry-native to 0.4.9 (#1431)
+* Fix: Set user on transaction (#1443)
```
Comment (bruno-garcia) [inline CHANGELOG.md:15]: This change affects only Spring, right?

```suggestion
* Fix: Set user on transaction on Spring (#1443)
```

File: sentry-spring/api/sentry-spring.api [hunk 3]
```diff
@@ -54,6 +54,12 @@ public class io/sentry/spring/SentrySpringServletContainerInitializer : javax/se
 	public fun onStartup (Ljava/util/Set;Ljavax/servlet/ServletContext;)V
 }
 
+public class io/sentry/spring/SentryUserFilter : javax/servlet/Filter {
```
Comment (bruno-garcia) [inline sentry-spring/api/sentry-spring.api:57]: Looks like we need to add these to the docs and a note on a migration plan for the next version (should be 5.0 I believe)?

File: sentry-spring/src/main/java/io/sentry/spring/SentryUserFilter.java [hunk 4]
```diff
@@ -0,0 +1,80 @@
...
+      if (IpAddressUtils.isDefault(user.getIpAddress())) {
+        // unset {{auto}} as it would set the server's ip address as a user ip address
+        user.setIpAddress(null);
+      }
+    }
+    hub.configureScope(scope -> scope.setUser(user));
+    chain.doFilter(request, response);
+  }
+
+  private void apply(final @NotNull User existingUser, final @Nullable User user) {
```
Comment (bruno-garcia) [inline sentry-spring/src/main/java/io/sentry/spring/SentryUserFilter.java:59]: Reading this method alone wasn't clear what `user` was in relation to `existingUser`.

What about something more specific like:

```suggestion
  private void apply(final @NotNull User existingUser, final @Nullable User userFromProvider) {
```

Or Maybe `existingUser` could be named `scopeUser`

File: sentry-spring-boot-starter/src/test/kotlin/io/sentry/spring/boot/SentryAutoConfigurationTest.kt [hunk 5]
```diff
@@ -319,11 +320,12 @@ class SentryAutoConfigurationTest {
         contextRunner.withPropertyValues("sentry.dsn=http://key@localhost/proj", "sentry.send-default-pii=true")
             .withConfiguration(UserConfigurations.of(SentryUserProviderConfiguration::class.java))
             .run {
-                val options = it.getBean(SentryProperties::class.java)
-                val userProviderEventProcessors = options.eventProcessors.filterIsInstance<SentryUserProviderEventProcessor>()
-                assertEquals(2, userProviderEventProcessors.size)
-                assertTrue(userProviderEventProcessors[0].sentryUserProvider is HttpServletRequestSentryUserProvider)
-                assertTrue(userProviderEventProcessors[1].sentryUserProvider is CustomSentryUserProvider)
+                val options = it.getBean("sentryUserFilter", FilterRegistrationBean::class.java).filter as SentryUserFilter
+                val userProviderEventProcessors = options.sentryUserProviders
```
Comment (marandaneto) [inline sentry-spring-boot-starter/src/test/kotlin/io/sentry/spring/boot/SentryAutoConfigurationTest.kt:324]: this is duplicated across tests, we could extract to `internal getUserProviderEventProcessors(it)`

File: sentry-spring/src/main/java/io/sentry/spring/SentryUserFilter.java [hunk 6]
```diff
@@ -0,0 +1,80 @@
...
+    if (user != null) {
+      Optional.ofNullable(user.getEmail()).ifPresent(existingUser::setEmail);
+      Optional.ofNullable(user.getId()).ifPresent(existingUser::setId);
+      Optional.ofNullable(user.getIpAddress()).ifPresent(existingUser::setIpAddress);
+      Optional.ofNullable(user.getUsername()).ifPresent(existingUser::setUsername);
+      if (user.getOthers() != null && !user.getOthers().isEmpty()) {
+        if (existingUser.getOthers() == null) {
+          existingUser.setOthers(new ConcurrentHashMap<>());
+        }
+        for (Map.Entry<String, String> entry : user.getOthers().entrySet()) {
```
Comment (marandaneto) [inline sentry-spring/src/main/java/io/sentry/spring/SentryUserFilter.java:69]:
```suggestion
        for (final Map.Entry<String, String> entry : user.getOthers().entrySet()) {
```

File: sentry-spring/src/main/java/io/sentry/spring/SentryUserFilter.java [hunk 7]
```diff
@@ -0,0 +1,80 @@
...
+          existingUser.getOthers().put(entry.getKey(), entry.getValue());
```
Comment (marandaneto) [inline sentry-spring/src/main/java/io/sentry/spring/SentryUserFilter.java:70]: should we check if the `key` already exists or it has precedence?

File: sentry-spring/src/main/java/io/sentry/spring/SentryUserProviderEventProcessor.java [hunk 8]
```diff
@@ -15,6 +15,10 @@
 import org.jetbrains.annotations.NotNull;
 import org.jetbrains.annotations.Nullable;
 
+/**
+ * Deprecated: instead of using event processor for setting user on events and transactions, user
+ * should be set on the scope using {@link SentryUserFilter}.
+ */
```
Comment (marandaneto) [inline sentry-spring/src/main/java/io/sentry/spring/SentryUserProviderEventProcessor.java:21]: I don't follow this comment, this filter should be only to address the missing user from transactions and not events, events should not be affected otherwise its a breaking change experience even for events or am I missing something?

Also, we should annotate with `@Deprecated`

File: sentry-spring/src/test/kotlin/io/sentry/spring/SentryUserFilterTest.kt [hunk 9]
```diff
@@ -0,0 +1,142 @@
...
+import org.springframework.mock.web.MockHttpServletRequest
+import org.springframework.mock.web.MockHttpServletResponse
+
+class SentryUserFilterTest {
+    class Fixture {
+        val hub = mock<IHub>()
+        val request = MockHttpServletRequest()
+        val response = MockHttpServletResponse()
+        val chain = mock<FilterChain>()
+        val options = SentryOptions()
```
Comment (marandaneto) [inline sentry-spring/src/test/kotlin/io/sentry/spring/SentryUserFilterTest.kt:25]: hub and options are not used outside of the method `getSut`, so they can be hidden in there, not really exposed here

**Comment by marandaneto** [comment]
@maciejwalkowiak we need docs for this

File: sentry-spring/src/main/java/io/sentry/spring/SentryUserFilter.java (hunk 4 above)
Comment (maciejwalkowiak) [reply sentry-spring/src/main/java/io/sentry/spring/SentryUserFilter.java]: Changed to `userFromProvider`.

File: sentry-spring/src/main/java/io/sentry/spring/SentryUserFilter.java (hunk 7 above)
Comment (maciejwalkowiak) [reply sentry-spring/src/main/java/io/sentry/spring/SentryUserFilter.java:70]: It has a precedence.

File: sentry-spring/src/main/java/io/sentry/spring/SentryUserProviderEventProcessor.java (hunk 8 above)
Comment (maciejwalkowiak) [reply sentry-spring/src/main/java/io/sentry/spring/SentryUserProviderEventProcessor.java]: This means that using this filter alone solves the problem of setting user on events and transactions. We keep it to not break codebases that do not add the filter. In long term: users should use filter and not this event processor.

File: sentry-spring/src/test/kotlin/io/sentry/spring/SentryUserFilterTest.kt (hunk 9 above)
Comment (maciejwalkowiak) [reply sentry-spring/src/test/kotlin/io/sentry/spring/SentryUserFilterTest.kt]: Refactored the filter a bit, to use `hub` instead of configuring scope.

File: sentry-spring/src/main/java/io/sentry/spring/SentryUserProviderEventProcessor.java (hunk 8 above)
Comment (marandaneto) [reply sentry-spring/src/main/java/io/sentry/spring/SentryUserProviderEventProcessor.java]: ah ok, `SentryInitBeanPostProcessor` still adds it, so `SentryUserProviderEventProcessor` will get executed for the Spring integration/events not causing a breaking change.

**Review by marandaneto — APPROVED** [review]
LGTM
