### PR TITLE
Pass OpenTelemetry span attributes into TracesSampler callback

### LINKED ISSUE #4192: Custom `TracesSamplerCallback` cannot access Spring request attributes when using OTEL
### Integration

sentry-opentelemetry-agentless-spring

### Java Version

17

### Version

8.1.0

### Steps to Reproduce

1. Create a project with `spring-boot-starter-web` (customer is using v2.7.11, but this is not relevant), `sentry-spring-boot-starter` and `sentry-opentelemetry-agentless-spring`
2. Follow the [docs](https://docs.sentry.io/platforms/java/guides/spring-boot/configuration/sampling/#setting-a-sampling-function) to set up a custom `TracesSamplerCallback` that returns different sample rates based on the request path
3. Start application and send HTTP request

Reported by pretchu in this [Discord thread](https://discord.com/channels/621778831602221064/1342443294159933450)

### Expected Result

Custom sample rate is returned based on request path, as correctly happens when using the SDK in non-OTEL mode.

### Actual Result

`context.getCustomSamplingContext()` is always `null`, hence the request path cannot be inspected to make a sampling decision.

### PR DESCRIPTION
**Pull request by adinauer**
## :scroll: Description

`SamplingContext` now has a `getAttribute` method granting access to OpenTelemetry span attributes when Sentry is used in OpenTelemetry mode.

## :bulb: Motivation and Context

Fixes #4192

## :pencil: Checklist

- [ ] I added tests to verify the changes.
- [ ] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled.
- [ ] I updated the docs if needed.
- [ ] I updated the wizard if needed.
- [ ] Review from the native team if needed.
- [ ] No breaking change or entry added to the changelog.
- [ ] No breaking change for hybrid SDKs or communicated to hybrid SDKs.

### CODE REVIEW

File: sentry/src/test/java/io/sentry/TracesSamplerTest.kt [hunk 1]
```diff
@@ -402,9 +414,60 @@ class TracesSamplerTest {
...
-            SamplingContext(TransactionContext("name", "op"), null, 0.0)
+            SamplingContext(TransactionContext("name", "op"), null, 0.0, null)
         )
         assertTrue(decision.sampled)
         assertEquals(0.0, decision.sampleRand)
     }
+
+    @Test
+    fun `attributes can be accessed in callback`() {
+        val exception = Exception("faulty TracesSamplerCallback")
```
Comment (lcian) [inline sentry/src/test/java/io/sentry/TracesSamplerTest.kt:425]:
```suggestion
```

File: sentry-opentelemetry/sentry-opentelemetry-core/src/main/java/io/sentry/opentelemetry/SentrySampler.java [hunk 2]
```diff
@@ -135,6 +143,22 @@ public SamplingResult shouldSample(
     }
   }
 
+  private @NotNull Map<String, Object> toMapWithStringKeys(final @NotNull Attributes attributes) {
```
Comment (lcian) [inline sentry-opentelemetry/sentry-opentelemetry-core/src/main/java/io/sentry/opentelemetry/SentrySampler.java:146]:
```suggestion
  private static @NotNull Map<String, Object> toMapWithStringKeys(final @NotNull Attributes attributes) {
```

**Review by lcian — APPROVED** [review]
Left some minor nits but LGTM.

We are calling it `getAttribute` which could possibly be an API we will have on `Span` as part of the attributes API that is in the works. As far as I understand this new concept of attributes will correspond to the OTEL one we are using here, so I agree on this naming.

Let's not forget to update the relevant docs: https://docs.sentry.io/platforms/java/guides/spring-boot/configuration/sampling/#setting-a-sampling-function

File: sentry-opentelemetry/sentry-opentelemetry-core/src/main/java/io/sentry/opentelemetry/SentrySampler.java (hunk 2 above)
Comment (adinauer) [reply sentry-opentelemetry/sentry-opentelemetry-core/src/main/java/io/sentry/opentelemetry/SentrySampler.java:146]: Why would you make the method static?

Comment (lcian) [reply sentry-opentelemetry/sentry-opentelemetry-core/src/main/java/io/sentry/opentelemetry/SentrySampler.java:146]: Not really that important but it can just be static as it's not accessing any of the properties/methods of the object

Comment (adinauer) [reply sentry-opentelemetry/sentry-opentelemetry-core/src/main/java/io/sentry/opentelemetry/SentrySampler.java:146]: OK, I prefer defaulting to non-static and usually only have utils and factory method as static.
