### PR TITLE
Avoid NPEs from SDK in API like setTag, setData, setContext

### LINKED ISSUE #4224: Span.setData / Transaction.setData cause NullPointerException
### Integration

sentry

### Java Version

any

### Version

v7 + v8

### Steps to Reproduce

- setData(null, "x")
- setData("x", null)
- setData(null, null)

all of these cause an NPE

### Expected Result

just NoOp in that case (OTel also does that)

we can consider unsetting any current data with the same key, if a `null` value is set

### Actual Result

NPE

### PR DESCRIPTION
**Pull request by adinauer**
## :scroll: Description

Using the SDK and having to guard against `null` is not a nice experience. Instead the SDK now tries to do the right thing when it receives `null` on APIs like `setTag`, `setData`, `setContext`, `setExtra` etc.

This means the SDK will:
- NoOp if the `key` is `null` (maybe returning `null` if a return type is specified)
- Unset the previous value if the value is set to `null`

## :bulb: Motivation and Context

Fixes #4224

## :pencil: Checklist

- [ ] I added tests to verify the changes.
- [ ] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled.
- [ ] I updated the docs if needed.
- [ ] I updated the wizard if needed.
- [ ] Review from the native team if needed.
- [ ] No breaking change or entry added to the changelog.
- [ ] No breaking change for hybrid SDKs or communicated to hybrid SDKs.

### CODE REVIEW

File: sentry/src/main/java/io/sentry/Scope.java [hunk 1]
```diff
@@ -654,7 +674,10 @@ public void removeExtra(final @NotNull String key) {
    * @param value the context value
    */
   @Override
-  public void setContexts(final @NotNull String key, final @NotNull Object value) {
+  public void setContexts(final @Nullable String key, final @Nullable Object value) {
+    if (key == null) {
+      return;
+    }
```
Comment (lcian) [inline sentry/src/main/java/io/sentry/Scope.java:680]: I think we need to also unset if value is null here, like we do in the other overloads

Comment (lcian) [reply sentry/src/main/java/io/sentry/Scope.java:680]: Or maybe it will be handled by the below call? Not sure.

File: sentry/src/main/java/io/sentry/SentryTracer.java [hunk 2]
```diff
@@ -677,14 +677,11 @@ private void updateBaggageValues(final @NotNull Baggage baggage) {
...
-        // This is used in the spanFinishCallback, when the span isn't finished, but has a finish
-        // date
-        if (!span.isFinished() && span.getFinishDate() == null) {
-          return false;
-        }
+    for (final Span span : this.children) {
+      // This is used in the spanFinishCallback, when the span isn't finished, but has a finish
+      // date
+      if (!span.isFinished() && span.getFinishDate() == null) {
+        return false;
```
[the remark this answers is not in the document]
Comment (adinauer) [reply sentry/src/main/java/io/sentry/SentryTracer.java:684]: Ah yes, forgot to revert this.

File: sentry/src/main/java/io/sentry/Scope.java (hunk 1 above)
Comment (adinauer) [reply sentry/src/main/java/io/sentry/Scope.java:680]: Yeah, this is handled by `Contexts.put` so no need to duplicate it here.

**Review by lcian — APPROVED** [review]
LGTM

**Comment by lcian** [comment]
Flaky tests? Looks like they are failing after ac9ebcd37106e31ac787798e8dbf980e45741fc9

**Comment by adinauer** [comment]
I'm guessing it's the OkHttp change. I've set the timeouts since it ran into `SocketTimeoutException`
