### PR TITLE
fix: SentryClient overrides event with default data

### LINKED ISSUE #736: Default tags override event tags
In `SentryClient.java`, this is the implementation of `sendEvent`:

```java
 public void sendEvent(EventBuilder eventBuilder) {
        if (!Util.isNullOrEmpty(release)) {
            eventBuilder.withRelease(release.trim());
            if (!Util.isNullOrEmpty(dist)) {
                eventBuilder.withDist(dist.trim());
            }
        }

        if (!Util.isNullOrEmpty(environment)) {
            eventBuilder.withEnvironment(environment.trim());
        }

        if (!Util.isNullOrEmpty(serverName)) {
            eventBuilder.withServerName(serverName.trim());
        }

        for (Map.Entry<String, String> tagEntry : tags.entrySet()) {
            eventBuilder.withTag(tagEntry.getKey(), tagEntry.getValue());
        }

        for (Map.Entry<String, Object> extraEntry : extra.entrySet()) {
            eventBuilder.withExtra(extraEntry.getKey(), extraEntry.getValue());
        }

        runBuilderHelpers(eventBuilder);
        Event event = eventBuilder.build();
        sendEvent(event);
    }
```

In particular - default extras and tags, coming from a parsed DSN for example - seem to override event-specific extras and tags with the same key. I'd consider this unwanted behaviour. A default is nothing more than a default, i.e. a value that is reported when nothing else is there. But _if_ there is a specific value, then this specific value should take precedence.

My use case why I stumbled upon this was that I wanted to have a single tag to distinguish between fatal (reported the built-in uncaught exception handler of Sentry) and non-fatal (reported by my own machinery) crashes, and to mark them I wanted to introduce a tag `exception-type`. Since I cannot easily change the implementation of Sentry's uncaught exception handler, I thought I could simply give the tag `?tags=exception-type=fatal` as default parameter to my DSN and have this used by the exception handler events, while in my own events I'd configure my event `.withTag("exception-type=non-fatal")` and that would override the default value.

### PR DESCRIPTION
**Pull request by bruno-garcia**
Resolves #736

### CODE REVIEW

File: sentry/src/main/java/io/sentry/SentryClient.java [hunk 1]
```diff
@@ -148,32 +148,53 @@ public void sendEvent(Event event) {
...
+
+    /**
+     * Adds the SentryClient data into the builder without overriding existent data and builds the event.
+     * @param eventBuilder The event builder to potentially modify and to build the event.
+     * @return The event.
+     */
+    Event buildEvent(EventBuilder eventBuilder) {
+        Event workingEvent = eventBuilder.getEvent();
+
+        if (!Util.isNullOrEmpty(release) && workingEvent.getRelease() == null) {
```
Comment (kamilogorek) [inline sentry/src/main/java/io/sentry/SentryClient.java]: Can't you reuse `isNullOrEmpty` in both cases? Unless empty release in event is valid usecase.
Same goes for the rest of checks.

Comment (bruno-garcia) [reply sentry/src/main/java/io/sentry/SentryClient.java]: Personally I'd use `null` check everywhere. If we need to drop empty strings I'd do it in a single place (i.e right before sending on some event validation layer) but on each single operation over every string doing null or empty kind of sucks. And also all the `.trim()` calls everywhere. I don't want to change `Util.isNullOrEmpty` into a simple `null` check because that is a backward incompatible change though.
