### PR TITLE
Fix profiling init for Spring and Spring Boot w Agent auto-init

### LINKED ISSUE #4855: Profiler is not initialized when using spring-boot or spring with OTEL Agent
### Description

# Issue description
Due to the way classes are loaded in spring-boot or spring the OTEL Agent is not able to resolve the async-profiler classes needed to initialize profiling. This is only happening when the OTEL Agent is running in AUTO_INIT mode.

# Solution Brainstorm
Add a `@Configuration` class that takes care of initializing the profiler if it has not been initialized yet.

### PR DESCRIPTION
**Pull request by lbloder**
## :scroll: Description
Add `@Configuration` classes to initialize the profiler when running in OTEL Agent auto-init mode.

## :bulb: Motivation and Context
Fixes #4855

## :pencil: Checklist

- [ ] I added GH Issue ID _&_ Linear ID
- [ ] I added tests to verify the changes.
- [ ] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled.
- [ ] I updated the docs if needed.
- [ ] I updated the wizard if needed.
- [ ] Review from the native team if needed.
- [ ] No breaking change or entry added to the changelog.
- [ ] No breaking change for hybrid SDKs or communicated to hybrid SDKs.

### CODE REVIEW

File: sentry-spring-boot-jakarta/src/main/java/io/sentry/spring/boot/jakarta/SentryProfilerAutoConfiguration.java [hunk 1]
```diff
@@ -0,0 +1,13 @@
+package io.sentry.spring.boot.jakarta;
+
+import com.jakewharton.nopen.annotation.Open;
+import io.sentry.spring.jakarta.SentryProfilerConfiguration;
+import org.springframework.boot.autoconfigure.condition.ConditionalOnClass;
+import org.springframework.context.annotation.Configuration;
+import org.springframework.context.annotation.Import;
+
+@Configuration(proxyBeanMethods = false)
+@ConditionalOnClass(name = {"io.sentry.opentelemetry.agent.AgentMarker"})
```
Comment (lbloder) [inline sentry-spring-boot-jakarta/src/main/java/io/sentry/spring/boot/jakarta/SentryProfilerAutoConfiguration.java]: Make it conditional on the async profiler class too?

File: sentry-spring-jakarta/src/main/java/io/sentry/spring/jakarta/SentryProfilerConfiguration.java [hunk 2]
```diff
@@ -0,0 +1,94 @@
...
+ * implementations. This Configuration sets the profiler and converter on the options if that was
+ * the case.
+ */
+@Configuration(proxyBeanMethods = false)
+@Open
+public class SentryProfilerConfiguration {
+
+  @Bean
+  @ConditionalOnMissingBean(name = "sentryOpenTelemetryProfilerConfiguration")
+  public IContinuousProfiler sentryOpenTelemetryProfilerConfiguration() {
```
Comment (lbloder) [inline sentry-spring-jakarta/src/main/java/io/sentry/spring/jakarta/SentryProfilerConfiguration.java:27]: Extract init into util to streamline initialization code

File: sentry-spring-jakarta/src/main/java/io/sentry/spring/jakarta/SentryProfilerConfiguration.java [hunk 3]
```diff
@@ -0,0 +1,94 @@
...
+                SentryLevel.INFO,
+                "Successfully loaded continuous profiler via Spring Boot classloader");
+      }
+    }
+    return profiler;
+  }
+
+  @Bean
+  @ConditionalOnMissingBean(name = "sentryOpenTelemetryProfilerConverterConfiguration")
+  public IProfileConverter sentryOpenTelemetryProfilerConverterConfiguration() {
```
Comment (lbloder) [inline sentry-spring-jakarta/src/main/java/io/sentry/spring/jakarta/SentryProfilerConfiguration.java:40]: Extract init into util to streamline initialization code

**Comment by lbloder** [comment]
@sentry review

**Comment by lbloder** [comment]
@cursor review

File: sentry-async-profiler/src/test/java/io/sentry/asyncprofiler/init/AsyncProfilerInitUtilTest.kt [hunk 4]
```diff
@@ -0,0 +1,77 @@
...
+    assert(profiler is NoOpContinuousProfiler)
+  }
+
+  @Test
+  fun `initialize converter returns no-op converter if converter already initialized`() {
+    val options =
+      SentryOptions().also {
+        it.setProfileSessionSampleRate(1.0)
+        it.tracesSampleRate = 1.0
+        it.profilerConverter = AsyncProfilerProfileConverterProvider.AsyncProfilerProfileConverter()
```
[the remark this answers is not in the document]
Comment (lbloder) [reply sentry-async-profiler/src/test/java/io/sentry/asyncprofiler/init/AsyncProfilerInitUtilTest.kt]: It actually is a nested class in AsyncProfilerProfileConverterProvider

File: sentry-async-profiler/src/test/java/io/sentry/asyncprofiler/init/AsyncProfilerInitUtilTest.kt [hunk 5]
```diff
@@ -0,0 +1,77 @@
+import io.sentry.ILogger
```
[the remark this answers is not in the document]
Comment (lbloder) [reply sentry-async-profiler/src/test/java/io/sentry/asyncprofiler/init/AsyncProfilerInitUtilTest.kt:3]: Good catch, fixed.

File: sentry-async-profiler/src/test/java/io/sentry/asyncprofiler/init/AsyncProfilerInitUtilTest.kt [hunk 6]
```diff
@@ -0,0 +1,79 @@
...
+          JavaContinuousProfiler(mock<ILogger>(), "", 10, mock<ISentryExecutorService>())
+        )
+      }
+
+    val profiler = InitUtil.initializeProfiler(options)
+    assert(profiler is NoOpContinuousProfiler)
+  }
+
+  @Test
+  fun `initialize converter returns no-op converter if converter already initialized`() {
```
Comment (adinauer) [inline sentry-async-profiler/src/test/java/io/sentry/asyncprofiler/init/AsyncProfilerInitUtilTest.kt]: `m` should it simply return the existing one instead of noop that potentially causes profiling to break?

File: sentry-spring-7/src/main/java/io/sentry/spring7/SentryProfilerConfiguration.java [hunk 7]
```diff
@@ -0,0 +1,50 @@
...
+import io.sentry.NoOpProfileConverter;
+import io.sentry.Sentry;
+import io.sentry.SentryOptions;
+import io.sentry.util.InitUtil;
+import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
+import org.springframework.context.annotation.Bean;
+import org.springframework.context.annotation.Configuration;
+
+/**
+ * Handles late initialization of the profiler if the application is run with the OTEL Agent in
```
Comment (adinauer) [inline sentry-spring-7/src/main/java/io/sentry/spring7/SentryProfilerConfiguration.java]:
```suggestion
 * Handles late initialization of the profiler if the application is run with the Opentelemetry Agent in
```

File: sentry-spring-7/src/main/java/io/sentry/spring7/SentryProfilerConfiguration.java [hunk 8]
```diff
@@ -0,0 +1,50 @@
...
+ * implementations. This Configuration sets the profiler and converter on the options if that was
+ * the case.
+ */
+@Configuration(proxyBeanMethods = false)
+@Open
+public class SentryProfilerConfiguration {
+
+  @Bean
+  @ConditionalOnMissingBean(name = "sentryOpenTelemetryProfilerConfiguration")
+  public IContinuousProfiler sentryOpenTelemetryProfilerConfiguration() {
```
Comment (adinauer) [inline sentry-spring-7/src/main/java/io/sentry/spring7/SentryProfilerConfiguration.java:27]: Is there an expected order to these bean evaluations?

File: sentry-spring-boot-4/src/test/kotlin/io/sentry/spring/boot4/SentryAutoConfigurationTest.kt [hunk 9]
```diff
@@ -1037,6 +1040,39 @@ class SentryAutoConfigurationTest {
     }
   }
 
+  @Test
+  fun `when AgentMarker is on the classpath and ContinuousProfiling is enabled IContinuousProfiler and IProfileConverter beans are created and set on options`() {
+    SentryIntegrationPackageStorage.getInstance().clearStorage()
+    contextRunner
+      .withPropertyValues(
+        "sentry.dsn=http://key@localhost/proj",
+        "sentry.traces-sample-rate=1.0",
```
Comment (adinauer) [inline sentry-spring-boot-4/src/test/kotlin/io/sentry/spring/boot4/SentryAutoConfigurationTest.kt]: Should this also have `"sentry.profile-session-sample-rate=1.0",`?

File: sentry-spring-boot-4/src/test/kotlin/io/sentry/spring/boot4/SentryAutoConfigurationTest.kt [hunk 10]
```diff
@@ -1037,6 +1040,39 @@ class SentryAutoConfigurationTest {
...
+        "sentry.auto-init=false",
+        "debug=true",
+      )
+      .run {
+        assertThat(it).hasSingleBean(IContinuousProfiler::class.java)
```
Comment (adinauer) [inline sentry-spring-boot-4/src/test/kotlin/io/sentry/spring/boot4/SentryAutoConfigurationTest.kt:1091]: Is this currently simply asserting it has noop instances?

File: sentry-spring-boot-jakarta/src/main/java/io/sentry/spring/boot/jakarta/SentryProfilerAutoConfiguration.java (hunk 1 above)
Comment (adinauer) [reply sentry-spring-boot-jakarta/src/main/java/io/sentry/spring/boot/jakarta/SentryProfilerAutoConfiguration.java]: Sounds good, I see no reason to run this if profiler isn't there.

File: sentry/src/main/java/io/sentry/util/InitUtil.java [hunk 11]
```diff
@@ -46,4 +52,76 @@ public static boolean shouldInit(
 
     return previousOptions.getInitPriority().ordinal() <= newOptions.getInitPriority().ordinal();
   }
+
+  public static IContinuousProfiler initializeProfiler(@NotNull SentryOptions options) {
```
Comment (adinauer) [inline sentry/src/main/java/io/sentry/util/InitUtil.java:56]: `m` should we instead check if options already have a profiler / converter set (that's not noop) and return that?
IMO that makes it easier to reason about SDK init.
Looking at the tests it seems we're potentially replacing a working profiler / converter with noop (if misusing this util).

File: sentry-spring-7/src/main/java/io/sentry/spring7/SentryProfilerConfiguration.java (hunk 8 above)
Comment (lbloder) [reply sentry-spring-7/src/main/java/io/sentry/spring7/SentryProfilerConfiguration.java:27]: Thought about that again, and came to the conclusion that no, the order does not matter.
1) It doesn't matter if the Profiler or the Converter are created first as they have no direct dependency to each other.
2) Initially I was worried, that this needs to run after the original `SentryAutoConfiguration`, but based on the following scenarios it should not matter:
  a) No Agent -> Configuration does not run at all, as we depend on the AgentMarker
  b) Agent with AutoInit -> Sentry init happened through Agent and we set the profiler on the options. `SentryAutoConfiguration` shouldn't run at all as the dsn config should be done by OTEL. (caveat misconfiguration by also setting the dsn in application.properties)
  c1) Agent without AutoInit and `AutoConfiguration` runs before `SentryProfilerConfiguration` -> Sentry is enabled and profiler is already set if profiling is enabled, thus nothing happens.
  c2) Agent without AutoInit and `SentryAutoConfiguration` runs after `SentryProfilerConfiguration` -> Sentry is not yet enabled, thus `SentryProfilerConfiguration` does nothing and `SentryAutoConfiguration` configures profiler afterwards.

WDYT?

File: sentry-spring-boot-jakarta/src/main/java/io/sentry/spring/boot/jakarta/SentryProfilerAutoConfiguration.java (hunk 1 above)
Comment (lbloder) [reply sentry-spring-boot-jakarta/src/main/java/io/sentry/spring/boot/jakarta/SentryProfilerAutoConfiguration.java]: What might become an issue is, if we ever have a second `IContinuousProfiler` implementation, we also have to update the condition

**Review by adinauer — APPROVED** [review]
LGTM
