### PR TITLE
Fix wrong default environment in Session

### LINKED ISSUE #2381: sessions sent without an environment when environment option is not set - Android
### Description

Similar to https://github.com/getsentry/sentry-cocoa/issues/2411

If the environment is not set for the SDK errors will default to production. However, sessions are sent without an environment.

Expected outcome: sessions would be sent with an environment
Actual outcome: sessions are sent without an environment set

Steps To Reproduce

1. set the environment and release options
2. Send an error event and session
3. Observe that session and error event with the correct environment
4. repeat without setting the environment option
5. Observe the error event with an environment of production
6. Observe the session with no environment

### PR DESCRIPTION
**Pull request by lbloder**
## :scroll: Description
The environment getter in `SentryOptions` now returns "production" as default if not set.

## :bulb: Motivation and Context
Fixes #2381

## :pencil: Checklist

- [x] I reviewed the submitted code.
- [x] I added tests to verify the changes.
- [x] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled.
- [x] I updated the docs if needed.
- [x] Review from the native team if needed.
- [x] No breaking change or entry added to the changelog.
- [x] No breaking change for hybrid SDKs or communicated to hybrid SDKs.

### CODE REVIEW

File: sentry/src/main/java/io/sentry/SentryOptions.java [hunk 1]
```diff
@@ -773,8 +779,8 @@ public void setRelease(@Nullable String release) {
    *
    * @return the environment or null if not set
```
Comment (romtsn) [inline sentry/src/main/java/io/sentry/SentryOptions.java:780]:
```suggestion
   * @return the environment or 'production' if not set
```

**Review by romtsn — APPROVED** [review]

**Review by adinauer — APPROVED** [review]
