### PR TITLE
Provide API for attaching custom measurements to transactions

### LINKED ISSUE #2143: Flaky SentryTracerTest
### Description

```
io.sentry.SentryTracerTest > when idle transaction with children, finishes the transaction after the idle timeout FAILED
    Wanted but not invoked:
    hub.captureTransaction(
        <any>,
        <any>,
        <any>,
        <any>
    );
    -> at io.sentry.Hub.captureTransaction(Hub.java:606)
    However, there were exactly 5 interactions with this mock:
    hub.bindClient(
        Mock for ISentryClient, hashCode: 908635948
    );
    -> at io.sentry.SentryTracerTest$Fixture.<init>(SentryTracerTest.kt:33)
    hub.isEnabled();
    -> at io.sentry.Hub.bindClient(Hub.java:559)
    hub.getOptions();
    -> at io.sentry.SentryTracer.finish(SentryTracer.java:298)
    hub.configureScope(
        io.sentry.SentryTracer$$Lambda$206/0x000000080044f440@73dac022
    );
    -> at io.sentry.SentryTracer.finish(SentryTracer.java:331)
    hub.isEnabled();
    -> at io.sentry.Hub.configureScope(Hub.java:542)
        at app//io.sentry.Hub.captureTransaction(Hub.java:606)
        at app//io.sentry.SentryTracerTest.when idle transaction with children, finishes the transaction after the idle timeout(SentryTracerTest.kt:623)
```

### PR DESCRIPTION
**Pull request by adinauer**
## :scroll: Description

Add API for setting custom measurements.

## :bulb: Motivation and Context

https://github.com/getsentry/team-mobile/issues/51
Closes #2143

## :pencil: Checklist

- [x] I reviewed the submitted code
- [x] I added tests to verify the changes
- [ ] I updated the docs if needed
- [x] No breaking changes

## :crystal_ball: Next steps

### CODE REVIEW

File: sentry/src/main/java/io/sentry/SentryMeasurementUnit.java [hunk 1]
```diff
@@ -0,0 +1,37 @@
+package io.sentry;
+
+import java.util.Locale;
+import org.jetbrains.annotations.NotNull;
+
+public enum SentryMeasurementUnit {
```
Comment (marandaneto) [inline sentry/src/main/java/io/sentry/SentryMeasurementUnit.java:6]: The value class does not have a `Sentry` prefix.

Comment (romtsn) [reply sentry/src/main/java/io/sentry/SentryMeasurementUnit.java:6]: Do you mean we should remove it here?

Comment (marandaneto) [reply sentry/src/main/java/io/sentry/SentryMeasurementUnit.java:6]: Yes, the other one is called `MeasurementValue`.

Comment (romtsn) [reply sentry/src/main/java/io/sentry/SentryMeasurementUnit.java:6]: How about renaming it to `SentryMeasurementValue` rather? I feel like `MeasurementUnit` is a pretty common name, so I think it's better to keep it with the Sentry prefix for distinction

Comment (marandaneto) [reply sentry/src/main/java/io/sentry/SentryMeasurementUnit.java:6]: I'd leave this with you both, `MeasurementValue` is `@ApiStatus.Internal` so I'd be fine with it, btw, remember to remove such annotations now since they are public APIs.

Comment (adinauer) [reply sentry/src/main/java/io/sentry/SentryMeasurementUnit.java:6]: `MeasurementValue` is not public. You only call `setMeasurement` on the span but don't know that it will be converted internally. So I'd keep it marked as internal. Also feel like `MeasurementValue` is likely to have conflicts.

Comment (romtsn) [reply sentry/src/main/java/io/sentry/SentryMeasurementUnit.java:6]: as agreed with @adinauer we'll keep it as is

File: sentry/src/test/java/io/sentry/SentryTracerTest.kt [hunk 2]
```diff
@@ -382,13 +384,14 @@ class SentryTracerTest {
         transaction.setTag("myTag", "myNewValue")
         transaction.throwable = RuntimeException()
         transaction.setData("myData", "myNewValue")
-        transaction.name = "newName"
+        transaction.setMeasurement("myMetric", 2.0f)
```
Comment (romtsn) [inline sentry/src/test/java/io/sentry/SentryTracerTest.kt:387]:
```suggestion
	transaction.name = "newName"
        transaction.setMeasurement("myMetric", 2.0f)
```

File: sentry/src/main/java/io/sentry/SentryTracer.java [hunk 3]
```diff
@@ -506,6 +513,25 @@ public void setData(@NotNull String key, @NotNull Object value) {
     return this.root.getData(key);
   }
 
+  @Override
+  public void setMeasurement(@NotNull String name, float value) {
+    if (root.isFinished()) {
+      return;
+    }
+
+    this.measurements.put(name, new MeasurementValue(value, SentryMeasurementUnit.NONE.apiName()));
```
Comment (marandaneto) [inline sentry/src/main/java/io/sentry/SentryTracer.java:522]: You could just forward the call to the other `setMeasurement`, passing `SentryMeasurementUnit.NONE` as 3rd param.

Comment (marandaneto) [reply sentry/src/main/java/io/sentry/SentryTracer.java:522]: On Dart, `unit` is optional, does other SDKs default to `none`?

Comment (romtsn) [reply sentry/src/main/java/io/sentry/SentryTracer.java:522]: Dunno about other SDKs, but the spec says "defaulting to `none` if missing". https://develop.sentry.dev/sdk/event-payloads/transaction/
image

I am not sure if they mean that the Relay will set `none` or we should do it on the clients.

Comment (romtsn) [reply sentry/src/main/java/io/sentry/SentryTracer.java:522]: Seems like both python and js do not default to `none` but rather empty string (which I assume means "optional" in their case)
https://github.com/getsentry/sentry-python/blob/5348834cd6f6b2f877e10febd6ab963166519e04/sentry_sdk/tracing.py#L688

https://github.com/getsentry/sentry-javascript/blob/446a295d3db1b35dd280ba6ee5bdec43c2acbe9e/packages/tracing/src/transaction.ts#L81

Comment (marandaneto) [reply sentry/src/main/java/io/sentry/SentryTracer.java:522]: good catch, please raise this question with the spec and linked repos on client-infra.

File: CHANGELOG.md [hunk 4]
```diff
@@ -6,6 +6,7 @@
 
 - Make user segment a top level property ([#2257](https://github.com/getsentry/sentry-java/pull/2257))
 - Replace user `other` with `data` ([#2258](https://github.com/getsentry/sentry-java/pull/2258))
+- Provide API for attaching custom measurements to transactions ([#2260](https://github.com/getsentry/sentry-java/pull/2260))
```
Comment (adinauer) [inline CHANGELOG.md:9]: Should we update the title of the PR to match the changelog?

File: sentry/src/main/java/io/sentry/ISpan.java [hunk 5]
```diff
@@ -169,4 +169,27 @@ ISpan startChild(
    */
   @Nullable
   Object getData(@NotNull String key);
+
+  /**
+   * Set a measurement with NONE unit.
```
Comment (adinauer) [inline sentry/src/main/java/io/sentry/ISpan.java:174]:
```suggestion
   * Set a measurement without unit.
```

In case we decide to no longer default to NONE in the SDK.

File: sentry/src/main/java/io/sentry/SentryMeasurementUnit.java (hunk 1 above)
Comment (adinauer) [inline sentry/src/main/java/io/sentry/SentryMeasurementUnit.java:6]: Should we add a comment with link to the docs here?

```suggestion
/**
 * @see <a href="https://docs.sentry.io/platforms/python/guides/pyramid/performance/instrumentation/performance-metrics/">Develop Docs</a> 
 */
public enum SentryMeasurementUnit {
```

Not sure if there's user facing docs available.

File: sentry/src/main/java/io/sentry/SentryTracer.java (hunk 3 above)
Comment (adinauer) [reply sentry/src/main/java/io/sentry/SentryTracer.java:522]: - In case we decide to keep the default of `NONE` we could call the method with unit from the one without.
- In case we decide to drop the default in the SDK I'd keep them separate and keep the `@NotNull` on the `unit`.

File: sentry/src/test/java/io/sentry/SentryTracerTest.kt [hunk 6]
```diff
@@ -708,7 +712,7 @@ class SentryTracerTest {
 
     @Test
     fun `when idle transaction with children, finishes the transaction after the idle timeout`() {
-        val transaction = fixture.getSut(waitForChildren = true, idleTimeout = 10)
+        val transaction = fixture.getSut(waitForChildren = true, idleTimeout = 1000)
```
Comment (adinauer) [inline sentry/src/test/java/io/sentry/SentryTracerTest.kt:715]: 🤞

**Review by adinauer — COMMENTED** [review]
Mostly LGTM. Need to decide whether to set `NONE` as default in the SDK or not. If not there's some changes required.

File: sentry/src/main/java/io/sentry/SentryMeasurementUnit.java (hunk 1 above)
Comment (romtsn) [reply sentry/src/main/java/io/sentry/SentryMeasurementUnit.java:6]: I think I wouldn't want to link to python docs here :D changed it to Relay docs https://getsentry.github.io/relay/relay_metrics/enum.DurationUnit.html

Also I just noticed we only offer DurationUnit here actually (and also in the dart sdk cc @marandaneto), should we actually provide all of them? Or at least rename this one to something like `SentryMeasurementUnit.Duration` or so https://getsentry.github.io/relay/relay_metrics/enum.MetricUnit.html

**Comment by romtsn** [comment]
btw, I feel like we should change `float` to `Number` here, thoughts @adinauer @marandaneto ? Because if we keep float, then we'd send something like 
```
"screen_load_count": {
	"value": 1.0,
	"unit": "day"
}
```

which in turn, would be displayed like this in the Sentry UI:
image

and I think it doesn't look nice.

File: sentry/src/main/java/io/sentry/SentryMeasurementUnit.java (hunk 1 above)
Comment (adinauer) [reply sentry/src/main/java/io/sentry/SentryMeasurementUnit.java:9]: Yeah we can add more units. Oopsie on the docs link. Just hit search and didn't notice where it took me^^

**Comment by adinauer** [comment]
> change float to Number
Sounds good 👍

File: sentry/src/main/java/io/sentry/SentryMeasurementUnit.java [hunk 7]
```diff
@@ -0,0 +1,40 @@
+package io.sentry;
+
+import java.util.Locale;
+import org.jetbrains.annotations.NotNull;
+
+/**
+ * <a href="https://getsentry.github.io/relay/relay_metrics/enum.DurationUnit.html">Develop Docs</a>
+ */
+public enum SentryMeasurementUnit {
```
Comment (philipphofmann) [inline sentry/src/main/java/io/sentry/SentryMeasurementUnit.java:9]: `h`: MeasurementUnit are actually 3 different enums in Python; see 
https://github.com/getsentry/sentry-python/blob/37e165edd633bfde5927150633193bc1bf41eab1/sentry_sdk/_types.py#L53-L82. Relay calls them MetricUnit and they kind of align with Python, see https://getsentry.github.io/relay/relay_metrics/enum.MetricUnit.html

I know that we already implemented this like that in Dart, https://github.com/getsentry/sentry-dart/pull/1011, but maybe we should reconsider before moving forward.

We could define an interface for `SentryMeasurementUnit` and create different enums implementing the interface for duration, information, fraction, custom. 

Or we could create inner enums inside a class
```JAVA
public class SentryMeasurementUnit2 {
  public static enum Duration {
    SECOND, MINUTE
  }

  public enum Information {

  }
}
```

File: sentry/src/main/java/io/sentry/SentryMeasurementUnit.java [hunk 8]
```diff
@@ -0,0 +1,40 @@
...
+
+  /** Week (`"week"`), 604,800 seconds. */
+  WEEK,
+
+  /** Untyped value without a unit. */
+  NONE;
+
+  public @NotNull String apiName() {
+    return name().toLowerCase(Locale.ROOT);
+  }
```
Comment (philipphofmann) [inline sentry/src/main/java/io/sentry/SentryMeasurementUnit.java:39]: `m`: Does this have to be public? I don't think you need this as a user.

**Review by philipphofmann — COMMENTED** [review]
One important question about the API.

File: CHANGELOG.md (hunk 4 above)
[the remark this answers is not in the document]
Comment (romtsn) [reply CHANGELOG.md:9]: But this sounds like *we are* attaching custom measurements which isn't true :)

File: sentry/src/main/java/io/sentry/SentryMeasurementUnit.java (hunk 7 above)
Comment (romtsn) [reply sentry/src/main/java/io/sentry/SentryMeasurementUnit.java:9]: Agree, see my comment https://github.com/getsentry/sentry-java/pull/2260#discussion_r983365457. @marandaneto are you open to changing it for dart?

**Comment by marandaneto** [comment]
> btw, I feel like we should change `float` to `Number` here, thoughts @adinauer @marandaneto ? Because if we keep float, then we'd send something like
> 
> ```
> "screen_load_count": {
> 	"value": 1.0,
> 	"unit": "day"
> }
> ```
> 
> which in turn, would be displayed like this in the Sentry UI: image
> 
> and I think it doesn't look nice.
> 
> Worth noting, that if we don't send any units at all, then the frontend does not format it, and it just looks fine: image

it's a `num` in Dart, so it can be an `int` or `double`.

File: sentry/src/main/java/io/sentry/SentryMeasurementUnit.java (hunk 7 above)
Comment (marandaneto) [reply sentry/src/main/java/io/sentry/SentryMeasurementUnit.java:9]: Apparently, I only checked the [linked relay source code](https://github.com/getsentry/relay/blob/ed3a521f773ecd4bf9a2aefd7af80080d56d0841/relay-common/src/constants.rs#L353-L374) and didn't see the other ones, we have to fix this.

File: sentry/src/main/java/io/sentry/SentryMeasurementUnit.java (hunk 8 above)
Comment (romtsn) [reply sentry/src/main/java/io/sentry/SentryMeasurementUnit.java]: it's not for the user but for the sentry-android module where we use it directly

File: sentry/src/main/java/io/sentry/SentryMeasurementUnit.java (hunk 7 above)
Comment (marandaneto) [reply sentry/src/main/java/io/sentry/SentryMeasurementUnit.java]: I will address this here https://github.com/getsentry/sentry-dart/pull/1033

File: CHANGELOG.md (hunk 4 above)
[the remark this answers is not in the document]
Comment (philipphofmann) [reply CHANGELOG.md:9]: Then what about `API for attaching custom measurements to transactions`?

File: sentry/src/main/java/io/sentry/SentryMeasurementUnit.java [hunk 9]
```diff
@@ -0,0 +1,98 @@
+package io.sentry;
+
+import java.util.Locale;
+import org.jetbrains.annotations.NotNull;
+
+/**
+ * <a href="https://getsentry.github.io/relay/relay_metrics/enum.DurationUnit.html">Develop Docs</a>
+ */
+public interface SentryMeasurementUnit {
+  enum Duration implements SentryMeasurementUnit {
```
Comment (philipphofmann) [inline sentry/src/main/java/io/sentry/SentryMeasurementUnit.java:10]: Thanks 😊

File: CHANGELOG.md (hunk 4 above)
[the remark this answers is not in the document]
Comment (romtsn) [reply CHANGELOG.md:9]: I thought about it, but everywhere we use imperative verbs like Make,Add,Replace,etc. so I used Provide here. But I can change it if you're insisting, doesn't matter much :)

File: sentry/src/main/java/io/sentry/SentryMeasurementUnit.java (hunk 8 above)
Comment (marandaneto) [reply sentry/src/main/java/io/sentry/SentryMeasurementUnit.java]: You can annotate with @internal if needed

File: sentry/src/main/java/io/sentry/SentryMeasurementUnit.java [hunk 10]
```diff
@@ -0,0 +1,109 @@
...
+
+  enum Fraction implements SentryMeasurementUnit {
+    /** Floating point fraction of `1`. */
+    RATIO,
+
+    /** Ratio expressed as a fraction of `100`. `100%` equals a ratio of `1.0`. */
+    PERCENT;
+  }
+
+  final class Custom implements SentryMeasurementUnit {
```
Comment (romtsn) [inline sentry/src/main/java/io/sentry/SentryMeasurementUnit.java:90]: I'm not entirely sure about this, would require creating a new class instance for every custom unit. If it was Kotlin, I'd have used inline classes, problem solved.

In theory we could provide one more `setMeasurement` overload which accepts a plain String, but also not sure if it's better.

**Comment by romtsn** [comment]
@adinauer @philipphofmann @marandaneto ready for review once again

**Comment by romtsn** [comment]
@vaind looks like I made app with sentry start up faster than without sentry 🤣

**Comment by vaind** [comment]
> @vaind looks like I made app with sentry start up faster than without sentry 🤣

🥇 

I should probably make it re-run the whole suite in this case.

File: sentry-android-core/src/main/java/io/sentry/android/core/ActivityFramesTracker.java [hunk 11]
```diff
@@ -104,9 +102,9 @@ public synchronized void setMetrics(
       return;
     }
 
-    final MeasurementValue tfValues = new MeasurementValue(totalFrames, NONE_UNIT);
-    final MeasurementValue sfValues = new MeasurementValue(slowFrames, NONE_UNIT);
-    final MeasurementValue ffValues = new MeasurementValue(frozenFrames, NONE_UNIT);
+    final MeasurementValue tfValues = new MeasurementValue(totalFrames, null);
+    final MeasurementValue sfValues = new MeasurementValue(slowFrames, null);
+    final MeasurementValue ffValues = new MeasurementValue(frozenFrames, null);
```
Comment (marandaneto) [inline sentry-android-core/src/main/java/io/sentry/android/core/ActivityFramesTracker.java:107]: We default to `none` on Flutter, and RN.
Any reason to change it?

File: sentry/src/main/java/io/sentry/SentryMeasurementUnit.java (hunk 10 above)
Comment (marandaneto) [reply sentry/src/main/java/io/sentry/SentryMeasurementUnit.java:90]: I'd keep it as it is, Relay does the same.
Some languages don't have overloads, so at least we keep it unified.

File: sentry-android-core/src/main/java/io/sentry/android/core/ActivityFramesTracker.java (hunk 11 above)
Comment (romtsn) [reply sentry-android-core/src/main/java/io/sentry/android/core/ActivityFramesTracker.java:107]: See last message 🤣 
image

**Comment by marandaneto** [comment]
> @adinauer @philipphofmann @marandaneto ready for review once again

Feature-wise all good.
Good catch with the missing units.
I'd leave your peers to do the final review.

File: sentry/src/main/java/io/sentry/ISpan.java [hunk 12]
```diff
@@ -169,4 +169,28 @@ ISpan startChild(
    */
   @Nullable
   Object getData(@NotNull String key);
+
+  /**
+   * Set a measurement without unit.
```
Comment (philipphofmann) [inline sentry/src/main/java/io/sentry/ISpan.java:174]: `l`: I think it would make sense to explain what happens, when you don't provide the unit, and what benefit you have when you provide the unit.

File: sentry/api/sentry.api [hunk 13]
```diff
@@ -2449,13 +2508,11 @@ public final class io/sentry/protocol/Gpu$JsonKeys {
...
-	public static final field MILLISECOND_UNIT Ljava/lang/String;
-	public static final field NONE_UNIT Ljava/lang/String;
-	public fun <init> (FLjava/lang/String;)V
-	public fun <init> (FLjava/lang/String;Ljava/util/Map;)V
+	public fun <init> (Ljava/lang/Number;Ljava/lang/String;)V
+	public fun <init> (Ljava/lang/Number;Ljava/lang/String;Ljava/util/Map;)V
 	public fun getUnit ()Ljava/lang/String;
 	public fun getUnknown ()Ljava/util/Map;
-	public fun getValue ()F
+	public fun getValue ()Ljava/lang/Number;
```
Comment (philipphofmann) [inline sentry/api/sentry.api:2515]: `h`: Aren't these breaking changes? If yes, I think we should deprecate the old methods.

File: sentry/src/main/java/io/sentry/SentryMeasurementUnit.java [hunk 14]
```diff
@@ -0,0 +1,111 @@
+package io.sentry;
+
+import java.util.Locale;
+import org.jetbrains.annotations.ApiStatus;
+import org.jetbrains.annotations.NotNull;
+
+/**
+ * <a href="https://getsentry.github.io/relay/relay_metrics/enum.MetricUnit.html#">Develop Docs</a>
+ */
+public interface SentryMeasurementUnit {
```
Comment (philipphofmann) [inline sentry/src/main/java/io/sentry/SentryMeasurementUnit.java:10]: `h`: Can we rename this? We also have `MeasurementValue` and not `SentryMeasurementValue`. Furthermore, I don't think there will be many naming clashes.
```suggestion
public interface MeasurementUnit {
```

**Review by philipphofmann — COMMENTED** [review]
Almost LGTM.

File: sentry/api/sentry.api (hunk 13 above)
Comment (romtsn) [reply sentry/api/sentry.api:2515]: the class is marked as internal, so we do not guarantee public api stability

File: sentry/src/main/java/io/sentry/SentryMeasurementUnit.java (hunk 10 above)
Comment (romtsn) [reply sentry/src/main/java/io/sentry/SentryMeasurementUnit.java:90]: what kind of comments would you like to add? There's a link to the develop docs explaining every unit though

File: sentry/src/main/java/io/sentry/SentryMeasurementUnit.java (hunk 14 above)
Comment (romtsn) [reply sentry/src/main/java/io/sentry/SentryMeasurementUnit.java:10]: tbh I'm fine with both, just wanted to keep it aligned with the dart implementation. But I see now js also calls it just `MeasurementUnit`

File: sentry-android-core/src/main/java/io/sentry/android/core/ActivityFramesTracker.java (hunk 11 above)
Comment (romtsn) [reply sentry-android-core/src/main/java/io/sentry/android/core/ActivityFramesTracker.java:107]: or was it only meant for the custom custom measurements?

Comment (romtsn) [reply sentry-android-core/src/main/java/io/sentry/android/core/ActivityFramesTracker.java:107]: forget it, I just re-read the thread and it makes sense to have `none` here. thanks for pointing out!

File: sentry/src/main/java/io/sentry/ISpan.java [hunk 15]
```diff
@@ -169,4 +169,28 @@ ISpan startChild(
...
+   *
+   * <p>NOTE: Setting a measurement with the same name on the same transaction multiple times only
```
[the remark this answers is not in the document]
Comment (romtsn) [reply sentry/src/main/java/io/sentry/ISpan.java:176]: good point 👍

File: sentry/src/main/java/io/sentry/SentryMeasurementUnit.java (hunk 10 above)
Comment (romtsn) [reply sentry/src/main/java/io/sentry/SentryMeasurementUnit.java:90]: I've added some comments, mainly deriving from the Relay docs, lemme know if that works.

File: sentry/src/main/java/io/sentry/protocol/MeasurementValue.java [hunk 16]
```diff
@@ -18,32 +19,31 @@
 @ApiStatus.Internal
```
Comment (marandaneto) [inline sentry/src/main/java/io/sentry/protocol/MeasurementValue.java:19]: This should not be `@ApiStatus.Internal` anymore I believe.

Comment (romtsn) [reply sentry/src/main/java/io/sentry/protocol/MeasurementValue.java:19]: why not?

Comment (marandaneto) [reply sentry/src/main/java/io/sentry/protocol/MeasurementValue.java:19]: Because it's officially part of the event protocol.

File: sentry/src/test/java/io/sentry/SentryTracerTest.kt [hunk 17]
```diff
@@ -828,4 +828,22 @@ class SentryTracerTest {
             anyOrNull(),
         )
     }
+
+    @Test
+    fun `setting the same measurement multiple times only keeps latest value`() {
```
Comment (philipphofmann) [inline sentry/src/test/java/io/sentry/SentryTracerTest.kt:833]: Thanks 🙏

**Review by philipphofmann — APPROVED** [review]
LGTM, thanks @romtsn, and @adinauer.

File: sentry/src/main/java/io/sentry/protocol/MeasurementValue.java (hunk 16 above)
Comment (romtsn) [reply sentry/src/main/java/io/sentry/protocol/MeasurementValue.java:19]: hmm, should we also unmark [SentrySpan](https://github.com/getsentry/sentry-java/blob/main/sentry/src/main/java/io/sentry/protocol/SentrySpan.java) and [SentryTransaction](https://github.com/getsentry/sentry-java/blob/main/sentry/src/main/java/io/sentry/protocol/SentryTransaction.java)?  They are also part of the documented protocol

Comment (marandaneto) [reply sentry/src/main/java/io/sentry/protocol/MeasurementValue.java:19]: I guess so, I'd not block this PR for this tho.
Just mentioned because it touches this file specifically, it was an internal API and now it's not anymore.
We likely need to remove the internals from SDKs now (related to performance), Dart should have some as well.

File: sentry/src/main/java/io/sentry/MeasurementUnit.java [hunk 18]
```diff
@@ -0,0 +1,132 @@
...
+ * <p>When using the units to custom measurements, Sentry will apply formatting to display
+ * measurement values in the UI.
+ *
+ * @see <a href="https://getsentry.github.io/relay/relay_metrics/enum.MetricUnit.html#">Develop
+ *     Docs</a>
+ */
+public interface MeasurementUnit {
+
+  /** Untyped value. */
+  String NONE = "none";
```
Comment (adinauer) [inline sentry/src/main/java/io/sentry/MeasurementUnit.java:23]: Should users be able to pass `NONE` to `setMeasurement` explicitly? They can't if it's a String since it expects a `MeasurementUnit` to be passed.

File: sentry/src/main/java/io/sentry/protocol/MeasurementValue.java (hunk 16 above)
Comment (adinauer) [reply sentry/src/main/java/io/sentry/protocol/MeasurementValue.java:19]: But these classes are not part of the user facing API are they? They're "internal" to the SDK. Shouldn't that imply the `@ApiStatus.Internal`?

**Review by adinauer — COMMENTED** [review]
LGTM, just two more questions around `NONE` and marking as internal.

File: sentry/src/main/java/io/sentry/MeasurementUnit.java (hunk 18 above)
Comment (romtsn) [reply sentry/src/main/java/io/sentry/MeasurementUnit.java:23]: Nope, they should use the setMeasurement overload without a unit for that purpose. We could mark NONE internal actually.

Comment (adinauer) [reply sentry/src/main/java/io/sentry/MeasurementUnit.java:23]: Sounds good

File: sentry/src/main/java/io/sentry/protocol/MeasurementValue.java (hunk 16 above)
Comment (romtsn) [reply sentry/src/main/java/io/sentry/protocol/MeasurementValue.java:19]: `SentryTransaction` is used in the EventProcessor for example, so it's technically not Internal. Same with `SentrySpan` and `MeasurementValue` if we unmark `SentryTransaction` internal.

I think we should generally revisit the public api of the sdk

Comment (adinauer) [reply sentry/src/main/java/io/sentry/protocol/MeasurementValue.java:19]: Thanks for the clarification. So I guess the plan is to remove all of the annotations in one PR and not remove it for `MeasurementValue` here?

Comment (romtsn) [reply sentry/src/main/java/io/sentry/protocol/MeasurementValue.java:19]: yeah, I'll create an issue for that

Comment (romtsn) [reply sentry/src/main/java/io/sentry/protocol/MeasurementValue.java:19]: https://github.com/getsentry/team-mobile/issues/57

**Comment by romtsn** [comment]
Thanks everyone for the reviews and opinions 🎉
