### PR TITLE
Fix UncaughtExceptionHandlerIntegration Memory Leak

### LINKED ISSUE #3266: UncaughtExceptionHandlerIntegration leaks memory
### Integration

sentry

### Java Version

17

### Version

7.6.0

### Steps to Reproduce

Cannot be very specific because sentry SDK is being used by a plugin within a framework, and within that environment we cannot reproduce the issue unless we are receiving production traffic

### Expected Result

no memory leak

### Actual Result

the UncaughtExceptionHandlerIntegration appears to occupy the majority of the heap, eventually resulting in memory exhaustion and a crash. 

On auditing the code it appears that 
https://github.com/getsentry/sentry-java/blob/28c9a83af55b119517dbd2fcf74975fb5822907b/sentry/src/main/java/io/sentry/UncaughtExceptionHandlerIntegration.java#L68-L81
causes a stack to form, which prevents any of the exeption handlers from being GC'd and results in OOM. No idea why that register method is being called over and over again

image

we are planning to simply turn the UncaughtExceptionHandler off in the options to resolve this issue, but it's weird that the Sentry SDK apparently behaves this way by default

### PR DESCRIPTION
**Pull request by lbloder**
Upon registration check if an `UncaughtExceptionHandlerIntegration` is already set as `defaultUncaughtExceptionHandler`, if so, set its `defaultExceptionHandler` as the default of the new `UncaughtExceptionHandlerIntegration`. 

## :bulb: Motivation and Context
Fixes #3266

## :pencil: Checklist

- [ ] I reviewed the submitted code.
- [ ] I added tests to verify the changes.
- [ ] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled.
- [ ] I updated the docs if needed.
- [ ] Review from the native team if needed.
- [ ] No breaking change or entry added to the changelog.
- [ ] No breaking change for hybrid SDKs or communicated to hybrid SDKs.

### CODE REVIEW

File: sentry/src/main/java/io/sentry/UncaughtExceptionHandlerIntegration.java [hunk 1]
```diff
@@ -75,7 +75,16 @@ public final void register(final @NotNull IHub hub, final @NotNull SentryOptions
...
+
+        if (currentHandler instanceof UncaughtExceptionHandlerIntegration) {
+          final UncaughtExceptionHandlerIntegration currentHandlerIntegration =
+              (UncaughtExceptionHandlerIntegration) currentHandler;
+          defaultExceptionHandler = currentHandlerIntegration.defaultExceptionHandler;
+        } else {
+          defaultExceptionHandler = currentHandler;
+        }
+
+        //        defaultExceptionHandler = currentHandler;
```
Comment (romtsn) [inline sentry/src/main/java/io/sentry/UncaughtExceptionHandlerIntegration.java:87]:
```suggestion
```

**Review by romtsn — APPROVED** [review]
nice!

**Review by adinauer — APPROVED** [review]
Thanks for taking care of this!
