### PR TITLE
No longer close OutputStream that is passed into JsonSerializer

### LINKED ISSUE #2027: If StdoutTransport and GsonSerializer are used, the logger does not work properly.
### Integration

sentry

### Java Version

11

### Version

5.2.0

### Steps to Reproduce

1. Set as follows

```java
@Bean
@Profile("local")
ITransportFactory local() {
     return new StdoutTransportFactory();
}

private static class StdoutTransportFactory implements ITransportFactory {
     @Override
     public ITransport create(SentryOptions options, RequestDetails requestDetails) {
         return new StdoutTransport(new GsonSerializer(options));
     }
}
```

2. And send a Sentry event in the middle of the log.

```java
log.info("before:");
Sentry.captureException(new RuntimeException());
log.info("after");
```

3. The output is:

```text
~~~~~~~: before
( blabla~~ )
( blabla~~ )
```

### Expected Result

It should output something like this:

```text
~~~~~~~: before
( blabla~~ )
( blabla~~ )
~~~~~~~: after
```

### Actual Result

```text
~~~~~~~: before
( blabla~~ )
( blabla~~ )
```

### PR DESCRIPTION
**Pull request by adinauer**
## :scroll: Description

No longer (auto) close the `OutputStream` that is passed into `JsonSerializer`. This caused problems when passing in `System.out` from `StdoutTransport` as it closed the stream.

## :bulb: Motivation and Context

Fixes #2027 for `6.x`

## :green_heart: How did you test it?
* Unit Test
* code sample

## :pencil: Checklist

- [x] I reviewed the submitted code
- [x] I added tests to verify the changes
- [ ] I updated the docs if needed
- [ ] No breaking changes

### CODE REVIEW

**Review by romtsn — APPROVED** [review]
LGTM 👍  Just one idea maybe - not sure if it'd make sense to introduce another method overload, which accepts a boolean like `autoClose`? Probably not needed though

File: sentry/src/main/java/io/sentry/JsonSerializer.java [hunk 1]
```diff
@@ -149,42 +149,48 @@ public <T> void serialize(@NotNull T entity, @NotNull Writer writer) throws IOEx
...
+
+        writer.write("\n");
+      } catch (Exception exception) {
+        options
+            .getLogger()
+            .log(SentryLevel.ERROR, "Failed to create envelope item. Dropping it.", exception);
       }
-      writer.flush();
     }
+    writer.flush();
```
Comment (marandaneto) [inline sentry/src/main/java/io/sentry/JsonSerializer.java:193]: should be likely in the `finally` block?

File: sentry/src/main/java/io/sentry/JsonSerializer.java [hunk 2]
```diff
@@ -149,42 +149,48 @@ public <T> void serialize(@NotNull T entity, @NotNull Writer writer) throws IOEx
...
-
-          writer.write("\n");
-        } catch (Exception exception) {
-          options
-              .getLogger()
-              .log(SentryLevel.ERROR, "Failed to create envelope item. Dropping it.", exception);
-        }
+    // we do not want to close these as we would also close the stream that was passed in
+    final BufferedOutputStream bufferedOutputStream = new BufferedOutputStream(outputStream);
+    final Writer writer = new BufferedWriter(new OutputStreamWriter(bufferedOutputStream, UTF_8));
```
Comment (marandaneto) [inline sentry/src/main/java/io/sentry/JsonSerializer.java:167]: Should we close the `writer` at least? or does it close the `bufferedOutputStream` as well?

**Comment by marandaneto** [comment]
> LGTM 👍 Just one idea maybe - not sure if it'd make sense to introduce another method overload, which accepts a boolean like `autoClose`? Probably not needed though

I think that this is actually needed, since the streams will be open or will wait to be GCed, we could rather make it closable by default, and the `StdoutTransport` transport pass `true` to this param when calling the `serialize` method.

**Comment by romtsn** [comment]
I've checked the usages of this method - basically everywhere we use try-with-resources around it, so we are safe internally. But yeah, if we expose this to the consumers, this may come as a surprise.

File: sentry/src/main/java/io/sentry/JsonSerializer.java (hunk 2 above)
Comment (adinauer) [reply sentry/src/main/java/io/sentry/JsonSerializer.java:167]: Each of them would close the `OutputStream` that is passed in when closed.

File: sentry/src/main/java/io/sentry/JsonSerializer.java (hunk 1 above)
Comment (adinauer) [reply sentry/src/main/java/io/sentry/JsonSerializer.java:193]: Only moved the code around. There's a catch block that only logs but doesn't throw out right before though.

**Comment by adinauer** [comment]
@marandaneto @romtsn do you still want me to implement a flag for autoClose after my explanation above?
