### PR TITLE
Remove profiler main thread io

### LINKED ISSUE #2317: DiskReadViolation in AndroidTransactionProfiler
### Integration

sentry-android

### Build System

Gradle

### AGP Version

7.3.1

### Proguard

Enabled

### Version

6.5.0

### Steps to Reproduce

Enable StrictMode.
Enable Profiling.
Launch app.

### Expected Result

No StrictMode violations.

### Actual Result
```
Non-fatal Exception: android.os.strictmode.DiskReadViolation
       at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1556)
       at libcore.io.BlockGuardOs.access(BlockGuardOs.java:69)
       at libcore.io.ForwardingOs.access(ForwardingOs.java:73)
       at android.app.ActivityThread$AndroidOs.access(ActivityThread.java:7884)
       at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:281)
       at java.io.File.exists(File.java:815)
       at io.sentry.android.core.AndroidTransactionProfiler.onTransactionStart(AndroidTransactionProfiler.java:118)
       at io.sentry.Hub.createTransaction(Hub.java:730)
       at io.sentry.Hub.startTransaction(Hub.java:665)
       at io.sentry.HubAdapter.e(HubAdapter.java:4)
       at io.sentry.android.core.ActivityLifecycleIntegration.startTracing(ActivityLifecycleIntegration.java:191)
       at io.sentry.android.core.ActivityLifecycleIntegration.onActivityCreated(ActivityLifecycleIntegration.java:283)
       at android.app.Application.dispatchActivityCreated(Application.java:392)
       at android.app.Activity.dispatchActivityCreated(Activity.java:1228)
       at android.app.Activity.onCreate(Activity.java:1505)
       at androidx.core.app.ComponentActivity.onCreate(ComponentActivity.java:88)
       at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:363)
       at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:217)
       at com.tubitv.fragmentoperator.activity.FoActivity.onCreate(FoActivity.kt:16)
       at io.opensea.context.MainActivity.onCreate(MainActivity.kt:27)
       at android.app.Activity.performCreate(Activity.java:7957)
       at android.app.Activity.performCreate(Activity.java:7946)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
       at androidx.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:2)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3530)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3707)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2220)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8016)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
```

### PR DESCRIPTION
**Pull request by stefanosiano**
## :scroll: Description
Removed a useless file exist check in AndroidTransactionProfiler
Offloaded AndroidTransactionProfiler methods to background threads using executor service

## :bulb: Motivation and Context
When using Android Strict Mode, the file io that was happening in the main thread (file existence checks) were generating warnings, as in this [issue](https://github.com/getsentry/sentry-java/issues/2317)

Closes #2317

## :green_heart: How did you test it?
I updated the unit tests

## :pencil: Checklist

- [x] I reviewed the submitted code
- [x] I added tests to verify the changes
- [ ] I updated the docs if needed
- [x] No breaking changes

### CODE REVIEW

File: sentry-android-core/src/main/java/io/sentry/android/core/AndroidTransactionProfiler.java [hunk 1]
```diff
@@ -138,9 +138,13 @@ private void init() {
     traceFilesDir = new File(tracesFilesDirPath);
   }
 
-  @SuppressLint("NewApi")
   @Override
   public synchronized void onTransactionStart(@NotNull ITransaction transaction) {
+    options.getExecutorService().submit(() -> onTransactionStartSafe(transaction));
```
Comment (stefanosiano) [inline sentry-android-core/src/main/java/io/sentry/android/core/AndroidTransactionProfiler.java:143]: We can either use the `options.getExecutorService().submit` or simply call the method directly.
The only remaining io method is `traceFilesDir.canWrite()` in `onTransactionStartSafe`
Is there any concern in using the executorService?

**Comment by romtsn** [comment]
Closes #2317

File: sentry-android-core/src/main/java/io/sentry/android/core/AndroidTransactionProfiler.java (hunk 1 above)
Comment (romtsn) [reply sentry-android-core/src/main/java/io/sentry/android/core/AndroidTransactionProfiler.java:143]: I think it should be fine, since we're using a single thread executor, so there should be no conflicts

**Review by romtsn — APPROVED** [review]

File: CHANGELOG.md [hunk 2]
```diff
@@ -6,6 +6,7 @@
 
 - Use correct set-cookie for the HTTP Client response object ([#2326](https://github.com/getsentry/sentry-java/pull/2326))
 - Fix NoSuchElementException in CircularFifoQueue when cloning a Scope ([#2328](https://github.com/getsentry/sentry-java/pull/2328))
+- Remove profiler main thread io ([#2348](https://github.com/getsentry/sentry-java/pull/2348))
```
[the remark this answers is not in the document]
Comment (stefanosiano) [reply CHANGELOG.md:9]: yep
