### PR TITLE
Respect maxSpans for nested child spans

### LINKED ISSUE #3058: MaxSpans is ignored for nested spans
### Integration

sentry

### Java Version

17

### Version

6.33.1

### Steps to Reproduce

The following code generates a high number of spans (1500) nested in a transaction (as direct parent) - `testInTransaction()`, or nested in a span - `testInNestedSpan`.

The Hub is configured with MaxSpan = 1000.

```java
private void testInTransaction() {
  ITransaction transaction = Sentry.startTransaction("Main Transaction", "task");
  createManySpans(transaction);
  transaction.finish();
}

private void testInNestedSpan() {
  ITransaction transaction = Sentry.startTransaction("Main Transaction", "task");
  ISpan parent = transaction.startChild("task", "Parent Span");
  createManySpans(parent);
  parent.finish();
  transaction.finish();
}

private static void createManySpans(ISpan parent) {
  for (int numSpan = 1; numSpan <= 1500; numSpan++) {
    ISpan innerSpan = parent.startChild("task", "Span Number = " + numSpan);
    innerSpan.finish();
  }
}
```

Execute both methods: `testInTransaction()` and `testInNestedSpan()`

### Expected Result

Given the configuration set to limit MaxSpan to 1000 spans, we should not more than 1000 spans in both transactions.

### Actual Result

While the first case (`testInTransaction`) works as expected. See:
image

The second case (`testInNestedSpan`) do not follow the 1000 Max spans constraints:
image

When looking at the code, the check to `getMaxSpans()` is done in [`SentryTrace.createChild`:441](https://github.com/getsentry/sentry-java/blob/main/sentry/src/main/java/io/sentry/SentryTracer.java#L455) but the actual add of child is done in [`SentryTrace.createChild`:346](https://github.com/getsentry/sentry-java/blob/main/sentry/src/main/java/io/sentry/SentryTracer.java#L393).

Here is the stack trace for calls to `SentryTracer.children.add()` for the first case:

- `createChild(SpanId, String, String, SentryDate, Instrumenter, SpanOptions)`:393, `SentryTracer` (io.sentry), SentryTracer.java
- `startChild(SpanId, String, String, SentryDate, Instrumenter, SpanOptions)`:324, `SentryTracer` (io.sentry), SentryTracer.java
- `startChild(String, String, SentryDate, Instrumenter, SpanOptions)`:121, `Span` (io.sentry), Span.java
- **`createChild(String, String, SentryDate, Instrumenter, SpanOptions)`:456, `SentryTracer` (io.sentry), SentryTracer.java** (<-- check on MaxSpans is done here)
- `startChild(String, String, SentryDate, Instrumenter, SpanOptions)`:418, `SentryTracer` (io.sentry), SentryTracer.java
- `startChild(String, String)`:432, `SentryTracer` (io.sentry), SentryTracer.java
- `createManySpans(ISpan)`
- `testInTransaction()`

And here is the stack trace for the second case:
- `createChild(SpanId, String, String, SentryDate, Instrumenter, SpanOptions)`:393, `SentryTracer` (io.sentry), SentryTracer.java
- `createChild(SpanId, String, String, SpanOptions)`:342, `SentryTracer` (io.sentry), SentryTracer.java
- `startChild(SpanId, String, String, SpanOptions)`:302, `SentryTracer` (io.sentry), SentryTracer.java
- `startChild(SpanId, String, String)`:284, `SentryTracer` (io.sentry), SentryTracer.java
- `startChild(String, String)`:132, `Span` (io.sentry), Span.java
- `createManySpans(ISpan)`
- `testInNestedSpan()`

We can see that in the second case, the `Span.startChild` "bypasses" the check on MaxSpans.

### PR DESCRIPTION
**Pull request by romtsn**
## :bulb: Motivation and Context

Closes #3058 

## :pencil: Checklist

- [x] I reviewed the submitted code.
- [x] I added tests to verify the changes.
- [x] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled.
- [x] I updated the docs if needed.
- [x] Review from the native team if needed.
- [x] No breaking change or entry added to the changelog.
- [x] No breaking change for hybrid SDKs or communicated to hybrid SDKs.

### CODE REVIEW

File: sentry/src/main/java/io/sentry/SentryTracer.java [hunk 1]
```diff
@@ -421,40 +421,51 @@ private ISpan createChild(
...
+          ? "main"
+          : Thread.currentThread().getName());
+      this.children.add(span);
+      return span;
+    } else {
+      hub.getOptions()
+        .getLogger()
+        .log(
+          SentryLevel.WARNING,
+          "Span operation: %s, description: %s dropped due to limit reached. Returning NoOpSpan.",
```
Comment (markushi) [inline sentry/src/main/java/io/sentry/SentryTracer.java]: Is it safe to potentially print this user-provided data?

**Review by markushi — APPROVED** [review]
LGTM! Just a minor concern.

File: sentry/src/main/java/io/sentry/SentryTracer.java (hunk 1 above)
Comment (romtsn) [reply sentry/src/main/java/io/sentry/SentryTracer.java]: yeah, I think we do print much more stuff in `debug` mode which is more sensitive 🙈
