### PR TITLE
fix: Do not include stacktrace into Timber message

### LINKED ISSUE #1177: Timber: Don't include stack trace frames in message
The Android Timber integration at the time it receives the `message` string from the library, already includes the `exception.toString()` into it:

https://github.com/getsentry/sentry-java/blob/5d8208dba4a7eb32696e38047ab21a4c7d435f3d/sentry-android-timber/src/main/java/io/sentry/android/timber/SentryTimberTree.kt#L48-L50

https://github.com/JakeWharton/timber/blob/4fd8e2a09c81931e9c9b004f45aea2937835278c/timber/src/main/java/timber/log/Timber.kt#L158

This becomes very noise in Sentry because the frames already show nicely in the stack trace view, but you also get it duplicated (and raw text) above in the message field.

If possible, override a more 'untreated' method of the timber logging interface, so we can format strings ourselves and not include frames in message.

Another proposed improvement is to log the breadcrumb category as `tag`, instead of `Timber`:

https://github.com/getsentry/sentry-java/blob/5d8208dba4a7eb32696e38047ab21a4c7d435f3d/sentry-android-timber/src/main/java/io/sentry/android/timber/SentryTimberTree.kt#L28

Other examples:

## Logback
https://github.com/getsentry/sentry-java/blob/5d8208dba4a7eb32696e38047ab21a4c7d435f3d/sentry-logback/src/main/java/io/sentry/logback/SentryAppender.java#L72-L74

https://github.com/getsentry/sentry-java/blob/5d8208dba4a7eb32696e38047ab21a4c7d435f3d/sentry-logback/src/main/java/io/sentry/logback/SentryAppender.java#L117

## M.E.Logging

https://github.com/getsentry/sentry-dotnet/blob/bfb18ac9dbe32b703886a22c72a0ac61a605539b/src/Sentry.Extensions.Logging/SentryLogger.cs#L68-L72

https://github.com/getsentry/sentry-dotnet/blob/bfb18ac9dbe32b703886a22c72a0ac61a605539b/src/Sentry.Extensions.Logging/SentryLogger.cs#L56

Proposed feature:

Option to group per message template. Override fingerprint so that only the temple is used. So all calls to logger at that location are grouped together regardless of where they came from (stack traces).

### PR DESCRIPTION
**Pull request by romtsn**
## :scroll: Description

* Overridden all Timber.Tree methods to have full control over the log message
* Supply `formatted` and `params` fields if the log-call was made with args
* Do not include stackframes into a message

How this looks now:
image

Grouping seems to work as well:
image

## :bulb: Motivation and Context

Closes #1177 

## :pencil: Checklist

- [x] I reviewed the submitted code
- [x] I added tests to verify the changes
- [ ] I updated the docs if needed
- [x] No breaking changes

## :crystal_ball: Next steps

1. We can't access tag from Timber because it's [package-private](https://github.com/JakeWharton/timber/blob/84b157605552e7b30f0d20e105d383b48ce8a030/timber/src/main/java/timber/log/Timber.java#L377-L386), so I had to drop it.
2. Since we set the Message ourselves, the stacktraces are not reported as breadcrumbs anymore (previously, Timber default implementation would put a stacktrace into a message variable and we would record a breadcrumb with the exception) - should we still do this?

### CODE REVIEW

File: sentry-android-timber/src/main/java/io/sentry/android/timber/SentryTimberTree.kt [hunk 1]
```diff
@@ -17,42 +17,218 @@ class SentryTimberTree(
...
+            if (message != null && args.isNotEmpty()) {
+                this.formatted = message.format(*args)
+            }
+            this.params = args.mapNotNull { it.toString() }
+        }
 
-        captureEvent(level, tag, message, throwable)
-        addBreadcrumb(level, message)
+        addBreadcrumb(level, sentryMessage)
+        captureEvent(level, sentryMessage, throwable)
```
Comment (marandaneto) [inline sentry-android-timber/src/main/java/io/sentry/android/timber/SentryTimberTree.kt:208]: The order here matters, first you capture the event and then add the breadcrumb, otherwise, the crumb is redundant.

**Comment by marandaneto** [comment]
> Since we set the Message ourselves, the stacktraces are not reported as breadcrumbs anymore (previously, Timber default implementation would put a stacktrace into a message variable and we would record a breadcrumb with the exception) - should we still do this?

No, the breadcrumb should not care about the stack trace, if there's an exception, we'll capture an event anyway.

**Comment by marandaneto** [comment]
> We can't access tag from Timber because it's [package-private](https://github.com/JakeWharton/timber/blob/84b157605552e7b30f0d20e105d383b48ce8a030/timber/src/main/java/timber/log/Timber.java#L377-L386), so I had to drop it.

That's a breaking change but not sure if it makes any difference or if somebody uses it as a filter on the Issues page.
@bruno-garcia ?

**Comment by romtsn** [comment]
> That's a breaking change but not sure if it makes any difference or if somebody uses it as a filter on the Issues page. @bruno-garcia ?

Yeah, timber isn't great when it comes to setting tags, because you need to invoke a separate method `Timber.tag` before calling the actual logging function. For `DebugTree` it infers the tag from a class name, in theory we could do the same if desired.

File: sentry-android-timber/src/main/java/io/sentry/android/timber/SentryTimberTree.kt (hunk 1 above)
Comment (romtsn) [reply sentry-android-timber/src/main/java/io/sentry/android/timber/SentryTimberTree.kt:208]: hm, actually from my tests, the breadcrumb was captured for the next event, is this how it's designed then?

Comment (marandaneto) [reply sentry-android-timber/src/main/java/io/sentry/android/timber/SentryTimberTree.kt:208]: 1. event
you capture the error/message (no breadcrumb about the error/message itself).
then you add the breadcrumb.

2. event
you capture the error/message (this time, there's a breadcrumb about event 1.)

This should be the way to go.

Comment (romtsn) [reply sentry-android-timber/src/main/java/io/sentry/android/timber/SentryTimberTree.kt:208]: Alright, clear. A follow-up question then: if the event was logged without a message, but just with a throwable (e.g. `Timber.e(Throwable("Test"))`), should we add the breadcrumb or not? 

Because the message is null in this case, so we either do not add it, or we put a stacktrace (or part of it) into the breadcrumb message.

Comment (marandaneto) [reply sentry-android-timber/src/main/java/io/sentry/android/timber/SentryTimberTree.kt:208]: If there's a message, let's use the message, otherwise let's create a message out of the throwable, but not with the stack trace, only with the description of the error, and then we change the type and category of this crumb, following the `error` type here https://develop.sentry.dev/sdk/event-payloads/breadcrumbs/

File: sentry-android-timber/src/main/java/io/sentry/android/timber/SentryTimberTree.kt [hunk 2]
```diff
@@ -17,42 +17,218 @@ class SentryTimberTree(
...
-     * Captures a Sentry Event if the min. level is equal or higher than the min. required level.
-     */
-    override fun log(priority: Int, tag: String?, message: String, throwable: Throwable?) {
         val level = getSentryLevel(priority)
+        val sentryMessage = Message().apply {
+            this.message = message
+            if (message != null && args.isNotEmpty()) {
+                this.formatted = message.format(*args)
+            }
+            this.params = args.mapNotNull { it.toString() }
```
Comment (bruno-garcia) [inline sentry-android-timber/src/main/java/io/sentry/android/timber/SentryTimberTree.kt:204]: nit: what about we map `null` to `"null"`? Could "collide" with an actual string that was "null" but the goal is to indicate what values where provided vs what wasn't. (%s, %s, %s = null, "bla", null), args would be : ["bla"] so not sure what position had the value vs null?

Alternatively we can omit args, not sure how much difference is in the UI at the end though

File: sentry-android-timber/src/main/java/io/sentry/android/timber/SentryTimberTree.kt (hunk 1 above)
Comment (bruno-garcia) [reply sentry-android-timber/src/main/java/io/sentry/android/timber/SentryTimberTree.kt:208]: +1 on what Manoel said here ^ 🚀

File: sentry-android-timber/src/test/java/io/sentry/android/timber/SentryTimberTreeTest.kt [hunk 3]
```diff
@@ -158,6 +160,9 @@ class SentryTimberTreeTest {
     }
 
     @Test
+    @Ignore(
```
Comment (bruno-garcia) [inline sentry-android-timber/src/test/java/io/sentry/android/timber/SentryTimberTreeTest.kt:163]: Should we make it public then? Just a getter?
Alternatively for testing purposes we could use reflection

**Review by bruno-garcia — APPROVED** [review]
❤️

File: sentry-android-timber/src/test/java/io/sentry/android/timber/SentryTimberTreeTest.kt (hunk 3 above)
Comment (romtsn) [reply sentry-android-timber/src/test/java/io/sentry/android/timber/SentryTimberTreeTest.kt:163]: I meant it's package-private in timber, we can't really get it, aside from reflection. So we have no way to expose it either. :) It's not only for testing, but also for end users - now when they do `Timber.tag("test"); Timber.e("issue")` we have no way to access this tag (that's also what I was talking about in the PR comments thread)

File: sentry-android-timber/src/main/java/io/sentry/android/timber/SentryTimberTree.kt (hunk 2 above)
Comment (romtsn) [reply sentry-android-timber/src/main/java/io/sentry/android/timber/SentryTimberTree.kt:204]: Makes total sense. Actually `mapNotNull` is useless here anyway, because, at first, it maps, and then appends the values that are not-null, but in our case we transform everything `toString()` so there will never be a null value. Will change it to `map` 👍 

I've been following the logback implementation though, and there it's filter not-null values, not sure if should be also changed? https://github.com/getsentry/sentry-java/blob/5d8208dba4a7eb32696e38047ab21a4c7d435f3d/sentry-logback/src/main/java/io/sentry/logback/SentryAppender.java#L100

File: sentry-android-timber/src/main/java/io/sentry/android/timber/SentryTimberTree.kt (hunk 1 above)
Comment (romtsn) [reply sentry-android-timber/src/main/java/io/sentry/android/timber/SentryTimberTree.kt]: Changed it, had to also additionally set category to `exception`, to align with when an error event happens (otherwise it'd show `generic` category as on the SS below)
image

**Comment by romtsn** [comment]
So the way to go with Timber I think we just do not support tags for now, if we get complaints/issues we can offer a reflection-based support (or automatically infer the tag from the classname). How does that sound?

**Comment by romtsn** [comment]
We could also mention it in the docs and link to an issue on github to vote for

**Comment by marandaneto** [comment]
> We could also mention it in the docs and link to an issue on github to vote for

Let's do this, but let's also add the missing tags feat. on the changelog changes.

File: sentry-android-timber/src/main/java/io/sentry/android/timber/SentryTimberTree.kt [hunk 4]
```diff
@@ -11,48 +11,225 @@ import timber.log.Timber
...
+        }
 
-    /**
-     * Captures a Sentry Event if the min. level is equal or higher than the min. required level.
-     */
-    override fun log(priority: Int, tag: String?, message: String, throwable: Throwable?) {
         val level = getSentryLevel(priority)
+        val sentryMessage = Message().apply {
+            this.message = message
+            if (message != null && args.isNotEmpty()) {
```
Comment (marandaneto) [inline sentry-android-timber/src/main/java/io/sentry/android/timber/SentryTimberTree.kt:202]: maybe check if `message.isNullOrEmpty()` as well

**Comment by romtsn** [comment]
Added a breaking change note on the changelog and linked it to the gh issue. Merging it when it's green
