### PR TITLE
Prevent NoOpHub from creating heavy SentryOptions objects.

### LINKED ISSUE #1263: NoOpHub.getOptions() should return a cached instance of SentryOptions instead of creating a new instance
_Platform:_
- [ ]  Android -> If yes, which Device API (and compileSdkVersion/targetSdkVersion/Build tools) version?
- [x]  Java -> If yes, which Java (and sourceCompatibility/targetCompatibility) version?
- [ ]  Kotlin -> If yes, which Kotlin (and jvmTarget) version?
- [ ]  NDK -> If yes, which NDK/CMake version?
- [ ]  React-Native -> If yes, which version?
- [ ]  Timber -> If yes, which version?
- [ ]  Log4j2 -> If yes, which version?
- [ ]  Logback -> If yes, which version?
- [x]  Spring -> If yes, which version? 5.3.3

_IDE:_
- [ ]  Android Studio -> If yes, which version?
- [ ]  IntelliJ -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Build system:_
- [ ]  Gradle -> If yes, which version?
- [ ]  Buck -> If yes, which version?
- [ ]  Bazel -> If yes, which version?
- [ ]  Maven -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [ ]  No

_Sentry Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [ ]  No

_Proguard/R8:_
- [ ]  Enabled
- [ ]  Disabled

_Platform installed with:_
- [ ] JCenter
- [ ] Bintray
- [ ] Maven Central
- [ ] Manually

The version of the SDK:
**4.1.0**

---
I have the following issue:

During performance testing we found a bunch of threads in thread dumps like this:

```
"http-nio-8080-exec-29" #76015 daemon prio=5 os_prio=0 cpu=5633.88ms elapsed=581.22s tid=0x00007f09e8031800 nid=0x149ea runnable  [0x00007f0878d57000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.10/Native Method)
	- parking to wait for  <0x00000000b0bc04f8> (a java.util.concurrent.FutureTask)
	at java.util.concurrent.locks.LockSupport.parkNanos(java.base@11.0.10/LockSupport.java:234)
	at java.util.concurrent.FutureTask.awaitDone(java.base@11.0.10/FutureTask.java:444)
	at java.util.concurrent.FutureTask.get(java.base@11.0.10/FutureTask.java:203)
	at io.sentry.HostnameCache.updateCache(HostnameCache.java:98)
	at io.sentry.HostnameCache.<init>(HostnameCache.java:62)
	at io.sentry.HostnameCache.<init>(HostnameCache.java:49)
	at io.sentry.HostnameCache.<init>(HostnameCache.java:45)
	at io.sentry.MainEventProcessor.<init>(MainEventProcessor.java:35)
	at io.sentry.SentryOptions.<init>(SentryOptions.java:1280)
	at io.sentry.NoOpHub.getOptions(NoOpHub.java:147)
	at io.sentry.HubAdapter.getOptions(HubAdapter.java:195)
	at io.sentry.spring.SentryRequestResolver.resolveHeadersMap(SentryRequestResolver.java:49)
	at io.sentry.spring.SentryRequestResolver.resolveSentryRequest(SentryRequestResolver.java:36)
	at io.sentry.spring.tracing.SentryTracingFilter.doFilterInternal(SentryTracingFilter.java:79)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
```

And then a bunch of threads (over 2K)  in WAITING state from the `SentryHostnameCache-0` pool:

```
"SentryHostnameCache-0" #218791 daemon prio=5 os_prio=0 cpu=0.14ms elapsed=457.02s tid=0x00007f0aa806a000 nid=0x18a14 waiting on condition  [0x00007f0872ffb000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.10/Native Method)
	- parking to wait for  <0x000000008785c230> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(java.base@11.0.10/LockSupport.java:194)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(java.base@11.0.10/AbstractQueuedSynchronizer.java:2081)
	at java.util.concurrent.LinkedBlockingQueue.take(java.base@11.0.10/LinkedBlockingQueue.java:433)
	at java.util.concurrent.ThreadPoolExecutor.getTask(java.base@11.0.10/ThreadPoolExecutor.java:1054)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.10/ThreadPoolExecutor.java:1114)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.10/ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(java.base@11.0.10/Thread.java:829)
```

I suspect this has something to do with the fact that initializing `SentryOptions` every time there is a request spawns creation of a bunch of other objects including `HostnameCache`. There is no reason to even do this if Sentry is disabled.

**Steps to reproduce:**
- Disable Sentry (no DSN) but still add SentryTracingFilter
- Generate high volume of traffic to the service
- Use jstack to create thread dumps

**Actual result:**
- Increasing count of threads stuck in WAITING state

**Expected result:**
- No rogue threads :)

### PR DESCRIPTION
**Pull request by maciejwalkowiak**
## :scroll: Description

Prevent NoOpHub from creating heavy SentryOptions objects.

## :bulb: Motivation and Context

Fixes #1263

## :pencil: Checklist

- [x] I reviewed the submitted code
- [ ] I added tests to verify the changes
- [ ] I updated the docs if needed
- [x] No breaking changes

### CODE REVIEW

File: sentry/src/main/java/io/sentry/SentryOptions.java [hunk 1]
```diff
@@ -1301,22 +1301,45 @@ public void setEnableDeduplication(final @Nullable Boolean enableDeduplication)
...
+    this(false);
+  }
+
+  /**
+   * Creates SentryOptions instance without initializing any of the internal parts.
+   *
+   * @param empty if options should be empty.
+   */
+  private SentryOptions(final boolean empty) {
+    if (!empty) {
```
Comment (marandaneto) [inline sentry/src/main/java/io/sentry/SentryOptions.java:1326]: I think the heaviest objects are inited. directly during the field declaration, maybe we should move all of them here in the ctor, so we can really do a cheap ctor.

Comment (maciejwalkowiak) [reply sentry/src/main/java/io/sentry/SentryOptions.java:1326]: The most heavy part is `MainEventProcessor` with `HostnameCache` that spins up a thread and `SentryExecutorService`. The rest is mainly no-op, except the serializer but i am not sure if it makes sense to complicate it any further.

Comment (marandaneto) [reply sentry/src/main/java/io/sentry/SentryOptions.java:1326]: sounds good

**Review by marandaneto — APPROVED** [review]
