### PR TITLE
Resolve HTTP Proxy parameters from the external configuration.

### LINKED ISSUE #1028: version 3.1.2 fails to use SENTRY_HTTP_PROXY_* variables
_Platform:_
- [ ]  Android -> If yes, which Device API (and compileSdkVersion/targetSdkVersion/Build tools) version?
- [X]  Java -> If yes, which Java (and sourceCompatibility/targetCompatibility) version?  1.8
- [ ]  Kotlin -> If yes, which Kotlin (and jvmTarget) version?
- [ ]  NDK -> If yes, which NDK/CMake version?
- [ ]  React-Native -> If yes, which version?
- [ ]  Timber -> If yes, which version?
- [ ]  Log4j2 -> If yes, which version?
- [ ]  Logback -> If yes, which version?
- [ ]  Spring -> If yes, which version?

_IDE:_
- [ ]  Android Studio -> If yes, which version?
- [X]  IntelliJ -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Build system:_
- [X]  Gradle -> If yes, which version?  6.5
- [ ]  Buck -> If yes, which version?
- [ ]  Bazel -> If yes, which version?
- [ ]  Maven -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [X]  No

_Sentry Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [X]  No

_Proguard/R8:_
- [ ]  Enabled
- [X]  Disabled

_Platform installed with:_
- [ ] JCenter
- [ ] Bintray
- [ ] Maven Central
- [X] Manually

The version of the SDK:
**3.1.2**

---
I have the following issue:

We were previously using 1.7.30 and specifying our HTTP proxy using these environment variables:

SENTRY_HTTP_PROXY_HOST=host
SENTRY_HTTP_PROXY_PORT=port

This was working fine.  After upgrading the 3.1.2, the proxy is not being set on the connection.  If I set the proxy manually via hardcode, it works again.  The documentation still claims that using the environment variables will work.

**Steps to reproduce:**
- upgrade working code from 1.7.30 to 3.1.2

**Actual result:**
- HTTP connections to Sentry fail because a proxy is required

**Expected result:**
- HTTP connections work

### PR DESCRIPTION
**Pull request by maciejwalkowiak**
## :loudspeaker: Type of change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring

## :scroll: Description

Resolve HTTP Proxy parameters from the external configuration.

In order to make Proxy properties resolution in non-Spring Boot application the same as in Spring Boot application, the names of the environment variables had to be changed from ones in 1.7.x

- `SENTRY_PROXY_HOST`
- `SENTRY_PROXY_PORT`
- `SENTRY_PROXY_USER`
- `SENTRY_PROXY_PASS`

In addition to that - `SentryOptions#proxy` object had to be changed into Java bean so that we are able to bind properties via Spring Boot environment.

## :bulb: Motivation and Context

Fixes #1028

## :green_heart: How did you test it?

Unit tests.

## :pencil: Checklist

- [x] I reviewed submitted code
- [x] I added tests to verify changes
- [x] All tests passing
- [ ] No breaking changes

### CODE REVIEW

File: sentry/src/main/java/io/sentry/SentryOptions.java [hunk 1]
```diff
@@ -238,6 +237,15 @@
     options.setRelease(propertiesProvider.getProperty("release"));
     options.setDist(propertiesProvider.getProperty("dist"));
     options.setServerName(propertiesProvider.getProperty("servername"));
+
+    final String proxyHost = propertiesProvider.getProperty("proxy.host");
+    final String proxyUser = propertiesProvider.getProperty("proxy.user");
+    final String proxyPass = propertiesProvider.getProperty("proxy.pass");
+    final String proxyPort = propertiesProvider.getProperty("proxy.port");
+
+    if (proxyHost != null && proxyPort != null) {
```
Comment (marandaneto) [inline sentry/src/main/java/io/sentry/SentryOptions.java:246]: is port mandatory? wondering if we can default to 80 for example if not set instead of not setting the proxy at all

Comment (maciejwalkowiak) [reply sentry/src/main/java/io/sentry/SentryOptions.java:246]: Good point. I'll default to 80. It will be consistent with 1.7

**Review by marandaneto — APPROVED** [review]
LGTM

**Comment by marandaneto** [comment]
@maciejwalkowiak this is ready to be merged, right? let's do it so we include it in the release next week.
