### PR TITLE
Fix SentryTransaction#getStatus NPE

### LINKED ISSUE #1268: SentryTransaction.getStatus throws NPE
SentryTransaction.getStatus throws NPE if the transaction is not finished yet.

https://github.com/getsentry/sentry-java/blob/b016da47681036b854fc62d3d141751d8c249a2a/sentry/src/main/java/io/sentry/SentryTransaction.java#L238-L242

it should probably be `context.getStatus()` instead as `this.getContexts().setTrace(this.context);` only happens on `finish`

### PR DESCRIPTION
**Pull request by maciejwalkowiak**
## :scroll: Description

Fix SentryTransaction#getStatus NPE

## :bulb: Motivation and Context

Fixes #1268.

## :pencil: Checklist

- [x] I reviewed the submitted code
- [x] I added tests to verify the changes
- [ ] I updated the docs if needed
- [x] No breaking changes

### CODE REVIEW

File: sentry/src/main/java/io/sentry/SentryTransaction.java [hunk 1]
```diff
@@ -238,7 +238,8 @@ Date getTimestamp() {
   @Override
   @Nullable
   public SpanStatus getStatus() {
-    return this.getContexts().getTrace().getStatus();
+    final SpanContext trace = this.getContexts().getTrace();
+    return trace != null ? trace.getStatus() : null;
```
Comment (marandaneto) [inline sentry/src/main/java/io/sentry/SentryTransaction.java:242]: why not `context.getStatus()`?
I could set a status and check for it, why do I need to wait the transaction to be finished?

Comment (maciejwalkowiak) [reply sentry/src/main/java/io/sentry/SentryTransaction.java:242]: Thanks Manoel, good point.

**Review by marandaneto — APPROVED** [review]
