### PR TITLE
[QA] Lazily load SentryOptions members

### LINKED ISSUE #2541: Initialize SentryOptions members lazily
### Description

When [SentryOptions.empty()](https://github.com/getsentry/sentry-java/blob/4b32504a16c1ffd2325208184a90b34a8252fb02/sentry/src/main/java/io/sentry/SentryOptions.java#L2047-L2049) is used (e.g. in a `NoOpHub`), we still eagerly initialize some of the class members, for example:
* [JsonSerializer](https://github.com/getsentry/sentry-java/blob/4b32504a16c1ffd2325208184a90b34a8252fb02/sentry/src/main/java/io/sentry/SentryOptions.java#L105)
* [ClientReportRecorder](https://github.com/getsentry/sentry-java/blob/4b32504a16c1ffd2325208184a90b34a8252fb02/sentry/src/main/java/io/sentry/SentryOptions.java#L369)
* [EnvelopeReader](https://github.com/getsentry/sentry-java/blob/4b32504a16c1ffd2325208184a90b34a8252fb02/sentry/src/main/java/io/sentry/SentryOptions.java#L102)

I think, those should be fine to initialize lazily, so in case of the empty options they do not cause potential issues. There was a recent customer report of an ANR caused by with Sentry frames in it (although the ANR is most likely not caused by Sentry, because there's nothing involved that should cause an ANR, but still we'd like to eliminate such issues):
```
main (runnable):tid=1 systid=27171 
       at io.sentry.JsonSerializer.<init>(JsonSerializer.java:84)
       at io.sentry.SentryOptions.<init>(SentryOptions.java:99)
       at io.sentry.SentryOptions.empty(SentryOptions.java:1899)
       at io.sentry.NoOpHub.<init>(NoOpHub.java:14)
       at io.sentry.NoOpHub.<clinit>(NoOpHub.java:12)
       at io.sentry.Sentry.<clinit>(Sentry.java:29)
       at io.sentry.HubAdapter.getSpan(HubAdapter.java:246)
       at io.sentry.instrumentation.file.FileIOSpanManager.startSpan(FileIOSpanManager.java:26)
       at io.sentry.instrumentation.file.SentryFileInputStream.init(SentryFileInputStream.java:65)
       at io.sentry.instrumentation.file.SentryFileInputStream.access$000(SentryFileInputStream.java:22)
       at io.sentry.instrumentation.file.SentryFileInputStream$Factory.create(SentryFileInputStream.java:137)
       at com.google.firebase.crashlytics.internal.settings.CachedSettingsIo.readCachedSettings(CachedSettingsIo.java:56)
       at com.google.firebase.crashlytics.internal.settings.SettingsController.getCachedSettingsData(SettingsController.java:235)
       at com.google.firebase.crashlytics.internal.settings.SettingsController.loadSettingsData(SettingsController.java:169)
       at com.google.firebase.crashlytics.internal.settings.SettingsController.loadSettingsData(SettingsController.java:154)
       at com.google.firebase.crashlytics.FirebaseCrashlytics.init(FirebaseCrashlytics.java:136)
       at com.google.firebase.crashlytics.CrashlyticsRegistrar.buildCrashlytics(CrashlyticsRegistrar.java:57)
       at com.google.firebase.crashlytics.CrashlyticsRegistrar.$r8$lambda$Pfd5XmDCFzNyAT9o9H6rDnTBQE4(CrashlyticsRegistrar.java)
       at com.google.firebase.crashlytics.CrashlyticsRegistrar$$InternalSyntheticLambda$1$ab347a8933944304e42539e3f0bc7a2eb5ded1d56c7a52feedae47ac52780cf7$0.create(CrashlyticsRegistrar.java:2)
       at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0(ComponentRuntime.java:132)
       at com.google.firebase.components.ComponentRuntime.$r8$lambda$4FqOW9eOQsvFYo-HpMfxCOnPQr0(ComponentRuntime.java)
       at com.google.firebase.components.ComponentRuntime$$InternalSyntheticLambda$0$784536aca87f12f75d3504e86fd606a2ca102f8312a2daf2c8c51b9b25617f63$0.get(ComponentRuntime.java:4)
       at com.google.firebase.components.Lazy.get(Lazy.java:53)
       at com.google.firebase.components.ComponentRuntime.doInitializeEagerComponents(ComponentRuntime.java:291)
       at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(ComponentRuntime.java:281)
       at com.google.firebase.FirebaseApp.initializeAllApis(FirebaseApp.java:584)
       at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:303)
       at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:267)
       at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:252)
       at com.google.firebase.provider.FirebaseInitProvider.onCreate(FirebaseInitProvider.java:51)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:2404)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:2374)
       at com.google.firebase.provider.FirebaseInitProvider.attachInfo(FirebaseInitProvider.java:45)
       at android.app.ActivityThread.installProvider(ActivityThread.java:7524)
       at android.app.ActivityThread.installContentProviders(ActivityThread.java:7041)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6790)
       at android.app.ActivityThread.access$1600(ActivityThread.java:255)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2100)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7941)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)
```

### PR DESCRIPTION
**Pull request by romtsn**
## :scroll: Description

There are members that we eagerly initialize, but we actually don't need them, so we can only init them when accessing for the first time:
* JsonSerializer
* EnvelopeReader
* DateProvider

Additionally, `AtomicClientReportStorage` was showing big numbers, so I made the lostEventCounts map a lazy one.

#### Before
Screenshot 2024-10-02 at 23 52 46

#### After

Screenshot 2024-10-03 at 00 42 10

#### Before
Screenshot 2024-10-03 at 13 44 22

#### After
Screenshot 2024-10-03 at 15 49 58

## :bulb: Motivation and Context

Closes #2541 

## :green_heart: How did you test it?
Manually, existing tests should cover this

## :pencil: Checklist

- [x] I reviewed the submitted code.
- [x] I added tests to verify the changes.
- [x] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled.
- [x] I updated the docs if needed.
- [x] Review from the native team if needed.
- [x] No breaking change or entry added to the changelog.
- [x] No breaking change for hybrid SDKs or communicated to hybrid SDKs.

### CODE REVIEW

File: sentry/src/main/java/io/sentry/SentryOptions.java [hunk 1]
```diff
@@ -415,8 +419,9 @@ public class SentryOptions {
   private boolean traceOptionsRequests = true;
 
   /** Date provider to retrieve the current date from. */
-  @ApiStatus.Internal
-  private @NotNull SentryDateProvider dateProvider = new SentryAutoDateProvider();
+  @ApiStatus.Internal private volatile @Nullable SentryDateProvider dateProvider;
```
Comment (stefanosiano) [inline sentry/src/main/java/io/sentry/SentryOptions.java:422]: We could use the `LazyEvaluator`, we'd just need to add a setValue() there.
Something like 
```
  private @NotNull LazyEvaluator<SentryDateProvider> dateProvider = new LazyEvaluator<>(() -> new SentryAutoDateProvider());


  public @NotNull SentryDateProvider getDateProvider() {
    return dateProvider.getValue();
  }
  public void setDateProvider(final @NotNull SentryDateProvider dateProvider) {
    this.dateProvider.setValue(dateProvider);
  }
```
wdyt?

File: sentry/src/main/java/io/sentry/clientreport/AtomicClientReportStorage.java [hunk 2]
```diff
@@ -14,25 +16,28 @@
 @ApiStatus.Internal
 final class AtomicClientReportStorage implements IClientReportStorage {
 
-  private final @NotNull Map<ClientReportKey, AtomicLong> lostEventCounts;
+  private final @NotNull LazyEvaluator<Map<ClientReportKey, AtomicLong>> lostEventCounts =
+      new LazyEvaluator<>(
```
Comment (romtsn) [inline sentry/src/main/java/io/sentry/clientreport/AtomicClientReportStorage.java:20]: oh, I realized we probably have to account for multithreaded access here, so also needs a double-checked locking probably

File: sentry/src/main/java/io/sentry/SentryOptions.java (hunk 1 above)
Comment (romtsn) [reply sentry/src/main/java/io/sentry/SentryOptions.java:422]: yeah that sounds good, but then we'd also have to rework the LazyEvaluator to support atomicity (as in make the value volatile and do double-checked locking when initializing the value). Wdyt? Or should we introduce a new (sub)type, like AtomicLazyEvaluator that does that?

Comment (adinauer) [reply sentry/src/main/java/io/sentry/SentryOptions.java:422]: Sounds good, should `value` in `LazyEvaluator` be `volatile`?
Should we use double checked locking, to avoid acquiring the lock for every read (then `volatile` would be required for sure)?

**Review by adinauer — APPROVED** [review]

File: sentry/src/main/java/io/sentry/SentryOptions.java [hunk 3]
```diff
@@ -605,7 +610,14 @@ public void setDiagnosticLevel(@Nullable final SentryLevel diagnosticLevel) {
    * @return the serializer
    */
   public @NotNull ISerializer getSerializer() {
-    return serializer;
+    if (serializer == null) {
+      synchronized (serializerLock) {
```
[the remark this answers is not in the document]
Comment (romtsn) [reply sentry/src/main/java/io/sentry/SentryOptions.java:614]: yep noted!

File: sentry/src/main/java/io/sentry/SentryOptions.java (hunk 1 above)
Comment (romtsn) [reply sentry/src/main/java/io/sentry/SentryOptions.java:422]: yeah that would be my idea, if we implement AtomicLazyEvaluator or something

Comment (stefanosiano) [reply sentry/src/main/java/io/sentry/SentryOptions.java:422]: we can change the `LazyEvaluator` directly, as the idea was to be thread safe anyway

File: sentry/src/main/java/io/sentry/clientreport/AtomicClientReportStorage.java (hunk 2 above)
Comment (adinauer) [reply sentry/src/main/java/io/sentry/clientreport/AtomicClientReportStorage.java:20]: Do you mean here or in `LazyEvaluator`?
Should work as is, just might be slow since it'll acquire the lock for every access to the map. So we traded startup performance for runtime performance.

File: sentry/src/main/java/io/sentry/clientreport/AtomicClientReportStorage.java [hunk 4]
```diff
@@ -14,25 +16,28 @@
...
+          () -> {
+            final Map<ClientReportKey, AtomicLong> modifyableEventCountsForInit =
+                new ConcurrentHashMap<>();
 
-  public AtomicClientReportStorage() {
-    final Map<ClientReportKey, AtomicLong> modifyableEventCountsForInit = new ConcurrentHashMap<>();
+            for (final DiscardReason discardReason : DiscardReason.values()) {
```
Comment (markushi) [inline sentry/src/main/java/io/sentry/clientreport/AtomicClientReportStorage.java:25]: @adinauer do you remember a specific reason for creating this map on init here, rather than adding entries on-demand within `void addCount`? I see it makes `addCount` fast, but I'm wondering if this even required, as this shouldn't be called very often.

Comment (adinauer) [reply sentry/src/main/java/io/sentry/clientreport/AtomicClientReportStorage.java:25]: IIRC I built it this way due to limited functionality of `ConcurrentHashMap` on older versions of Android. The way it is built now requires little and very specific synchronization at the cost of pre-initializing the map.

Here's some more details: https://github.com/getsentry/sentry-java/pull/1982/files/fff83e9b830bef077c21fc1e09ecfbf4fcef1a9c#r844882927

Comment (markushi) [reply sentry/src/main/java/io/sentry/clientreport/AtomicClientReportStorage.java:25]: Yeah makes a lot of sense! But `.addCount()` is only called in error cases and bound to network responses. So maybe it's better to have a slower `.addCount()` in favor of faster ctor?
I'm fine with LazyEvaluator too, just wondering what's best 😅

Comment (adinauer) [reply sentry/src/main/java/io/sentry/clientreport/AtomicClientReportStorage.java:25]: It's also called for sampling, backpressure, event processor etc. which might happen a lot and is not necessarily bound to network or other slow things. I prefer using `LazyEvaluator`.

File: sentry-samples/sentry-samples-android/src/main/AndroidManifest.xml [hunk 5]
```diff
@@ -73,7 +73,7 @@
         <meta-data android:name="io.sentry.dsn" android:value="https://1053864c67cc410aa1ffc9701bd6f93d@o447951.ingest.sentry.io/5428559" />
 
         <!--    how to enable Sentry's debug mode-->
-        <meta-data android:name="io.sentry.debug" android:value="${sentryDebug}" />
+        <meta-data android:name="io.sentry.debug" android:value="false" />
```
Comment (markushi) [inline sentry-samples/sentry-samples-android/src/main/AndroidManifest.xml:76]:
```suggestion
        <meta-data android:name="io.sentry.debug" android:value="${sentryDebug}" />
```

**Review by markushi — APPROVED** [review]
